/* Cuarto, semana 5, sesión 2: observación, pensamiento y análisis del aula. */
const aulaImage='aula-cuarto.jpeg';
const aulaRoutine=[
 {name:'Veo',icon:'👁️',question:'¿Qué podemos comprobar mirando la imagen?',options:['Hay mochilas y papeles en el suelo.','Todos los niños son desordenados.','Alguien se cayó.'],correct:0,feedback:'Las mochilas y los papeles se ven. No sabemos quién los dejó ni si alguien se cayó.'},
 {name:'Pienso',icon:'💭',question:'¿Qué podría pasar si caminamos por ese espacio?',options:['Alguien podría tropezar con una mochila.','Seguro que todos se van a caer.','La imagen demuestra que nadie cuida el aula.'],correct:0,feedback:'Es una posibilidad razonable, no un hecho ocurrido. Podemos decir «podría» y explicar qué nos hace pensarlo.'},
 {name:'Me pregunto',icon:'❓',question:'¿Qué pregunta nos ayudaría a comprender el problema?',options:['¿Por qué las mochilas están en el paso y dónde podemos guardarlas?','¿Quién es el más desordenado?','¿Qué videojuego prefieren?'],correct:0,feedback:'Preguntar por la causa y el espacio disponible nos ayuda a investigar antes de elegir una solución.'}
];
const aulaConcepts=[
 ['Necesidad','Poder caminar de forma segura por el aula.','Es importante para cuidarnos y participar en clase.'],
 ['Deseo','Sofía quiere una mochila nueva con luces, aunque la suya funciona.','Es una preferencia; las luces no son necesarias para guardar sus útiles.'],
 ['Problema','Las mochilas ocupan el paso entre los pupitres.','Es una dificultad que impide desplazarse con seguridad.'],
 ['Oportunidad','Crear un lugar identificado para guardar las mochilas y mantener libre el paso.','Es una posibilidad de mejora. El equipo deberá probar si funciona.']
];
const aulaConceptImages=['necesidad-aula.jpeg','deseo-sofia.jpeg','problema-mochilas.jpeg','oportunidad-mochilas.jpeg'];
const aulaCriteria=[['Disciplina y cumplimiento de códigos',2,'Escucha, respeta turnos y cumple los códigos de convivencia.'],['Trabajo en equipo',2,'Participa, cumple su rol y respeta las ideas de sus compañeros.'],['Actividad',4,'Identifica y justifica necesidad, deseo, problema y oportunidad: 1 punto por cada concepto.'],['Orden y organización',2,'Mantiene los materiales y el espacio ordenados; entrega la actividad clara y organizada.']];
function aulaEnabled(){return w5.grade===4&&w5.session===2&&!w5Root.hidden;}
function aulaPanel(content){return `<section class="aulaPanel">${content}</section>`;}
function aulaNav(previous,next){return `<nav class="aulaNav">${previous||'<span></span>'}${next||''}</nav>`;}
function aulaTeams(){const ts=w5Teams();return ts.length?ts:Array.from({length:6},(_,id)=>({id,name:'Grupo '+(id+1),color:w5Colors[id]}));}
const aulaOldActivity=w5S2Activity;
w5S2Activity=function(){
 if(!aulaEnabled())return aulaOldActivity();
 const p=w5Read();
 if(w5.step===0)return aulaPanel(`<div class="aulaPhoto"><img src="${aulaImage}" alt="Nuestra aula: mochilas en el paso y papeles en el suelo"><p class="aulaPhotoPrompt">🔎 Observen en silencio. Encuentren tres cosas que podrían mejorar.</p></div>${aulaNav('',`<button class="action primary" data-wstep="1">Compartir lo que pensamos →</button>`)}`);
 if(w5.step===1){const state=p.aulaRoutine||{phase:0,answers:{},ideas:{}},phase=Math.min(2,state.phase||0),r=aulaRoutine[phase],answer=state.answers?.[phase],correct=answer===r.correct;return aulaPanel(`<header class="aulaHead"><h2>Veo · Pienso · Me pregunto</h2><div class="aulaTabs">${aulaRoutine.map((x,i)=>`<button class="action ${i===phase?'primary':''}" data-aulaphase="${i}" ${i>phase&&state.answers?.[i-1]!==aulaRoutine[i-1].correct?'disabled':''}>${x.icon} ${x.name}</button>`).join('')}</div></header><div class="aulaRoutine"><img src="${aulaImage}" alt="Aula para observar y fundamentar nuestras ideas"><div><h3>${r.icon} ${r.name}</h3><p>${r.question}</p><div class="aulaChoices">${r.options.map((x,i)=>`<button class="action ${answer===i?'primary':''}" data-aulaanswer="${i}">${x}</button>`).join('')}</div>${answer!==undefined?`<p class="aulaFeedback" role="status">${correct?'✓ Buena elección.':'Revisa la evidencia y prueba otra opción.'} ${correct?r.feedback:''}</p>`:''}<label>La idea de nuestro curso<textarea data-aulaidea="${phase}" placeholder="La docente escribe una frase del curso…">${w5Esc(state.ideas?.[phase]||'')}</textarea></label></div></div>${aulaNav('<button class="action" data-wstep="0">← Volver a observar</button>',phase<2?`<button class="action primary" data-aulaphase="${phase+1}" ${correct?'':'disabled'}>Siguiente mirada →</button>`:`<button class="action primary" data-wstep="2" ${correct?'':'disabled'}>Analizar el caso →</button>`)}`);}
 if(w5.step===2){
  if(w5.item===2)return aulaPanel(`<div class="aulaWorksheet"><img src="actividad-cuarto.jpeg" alt="Ficha grupal: curso, grupo, nombres, roles y cuatro recuadros para pegar deseo, necesidad, problema y oportunidad"><div><h2>¡Trabajamos en equipo!</h2><ol><li>Escriban curso, grupo, nombres y roles.</li><li>Observen las imágenes entregadas.</li><li>Conversen y peguen cada imagen en su categoría.</li><li>Expliquen una elección: «La ubicamos aquí porque…».</li></ol><p class="aulaFeedback">Deseo · Necesidad · Problema · Oportunidad</p><a class="action" href="actividad-cuarto.jpeg" target="_blank" rel="noopener">Abrir hoja para imprimir ↗</a><button class="action primary" data-wstep="3">Ver rúbrica · 10 puntos →</button></div></div>${aulaNav('<button class="action" data-aulacase="1">← Volver al ejemplo</button>','<button class="action primary" data-wstep="3">Compartir y evaluar →</button>')}`);
  if(w5.item===1){const answers=p.aulaClassify||{},i=Math.max(0,Math.min(3,w5.aulaConceptIndex||0)),[kind,text,reason]=aulaConcepts[i],answer=answers[i],correct=answer===kind;return aulaPanel(`<header class="aulaHead"><h2>Observa, piensa y elige · ${i+1} de 4</h2><p>¿Necesidad, deseo, problema u oportunidad?</p></header><div class="aulaConceptSlide"><div class="aulaConceptPhoto"><img src="${aulaConceptImages[i]}" alt="${w5Esc(text)}"></div><div class="aulaConceptExercise"><h3>${text}</h3><p>Elijan la categoría y expliquen: «Es… porque…».</p><div class="aulaCategoryButtons">${aulaConcepts.map(([label])=>`<button class="action ${answer===label?'primary':''}" data-aulaclass="${i}" data-aulakind="${label}">${label}</button>`).join('')}</div>${answer?`<p class="aulaFeedback" role="status">${correct?'✓ '+kind+'. '+reason:'Prueben otra vez: ¿es algo importante, una preferencia, una dificultad o una posibilidad de mejora?'}</p>`:''}</div></div>${aulaNav(i?`<button class="action" data-aulaconcept="${i-1}">← Ejemplo anterior</button>`:'<button class="action" data-aulacase="0">← Leer el caso</button>',i<3?`<button class="action primary" data-aulaconcept="${i+1}" ${correct?'':'disabled'}>Siguiente ejemplo →</button>`:`<button class="action primary" data-aulacase="2" ${correct?'':'disabled'}>Nuestra actividad en grupo →</button>`)}`);}
  return aulaPanel(`<header class="aulaHead"><h2>¿Una mochila nueva resolvería el problema?</h2></header><div class="aulaCase"><img src="${aulaImage}" alt="Mochilas que ocupan el paso en el aula"><div><p>Al comenzar la clase, varias mochilas quedan entre los pupitres. Sofía tiene que rodearlas para llegar a su asiento.</p><p>Sofía quiere una mochila nueva con luces, aunque la que tiene funciona. El curso necesita moverse con seguridad.</p><p><b>Conversen:</b> ¿qué se observa?, ¿qué podría ocurrir?, ¿comprar otra mochila liberaría el paso?</p><p class="aulaFeedback">Una oportunidad: acordar un espacio para las mochilas, identificarlo y comprobar durante una semana si el paso queda libre.</p></div></div>${aulaNav('<button class="action" data-wstep="1">← Nuestras preguntas</button>','<button class="action primary" data-aulacase="1">Identificar los cuatro conceptos →</button>')}`);
 }
 if(w5.aulaScoreView==='table')return aulaPanel(`<header class="aulaHead"><h2>Registro de puntos · Grupos 1 a 5</h2><p>Selecciona los puntos de cada criterio. El total se calcula automáticamente.</p></header><table class="aulaGroupScores"><thead><tr><th scope="col">Criterio</th>${Array.from({length:5},(_,id)=>`<th scope="col" style="background:${w5Colors[id]}">Grupo ${id+1}</th>`).join('')}</tr></thead><tbody>${aulaCriteria.map(([title,max],i)=>`<tr><th scope="row">${title}<small>Máximo: ${max} puntos</small></th>${Array.from({length:5},(_,id)=>{const value=Number(p.aulaRubric?.[id]?.[i]||0);return `<td><select aria-label="Grupo ${id+1} · ${title}" data-aulascore="${i}" data-aulascoreteam="${id}">${Array.from({length:max*2+1},(_,n)=>n/2).map(n=>`<option value="${n}" ${value===n?'selected':''}>${n}</option>`).join('')}</select></td>`;}).join('')}</tr>`).join('')}</tbody><tfoot><tr><th scope="row">TOTAL / 10</th>${Array.from({length:5},(_,id)=>`<td><output aria-label="Total Grupo ${id+1}">${(p.aulaRubric?.[id]||[0,0,0,0]).reduce((sum,n)=>sum+Number(n),0)} / 10</output></td>`).join('')}</tr></tfoot></table><p class="aulaFeedback" role="status">Guardado automático · 4.º ${w5.course} · Los puntos de cada grupo se conservan en este navegador.</p>${aulaNav('<button class="action" data-aulatable="rubric">← Ver rúbrica y criterios</button>','<button class="action" data-deckcover>Volver a la portada</button>')}`);
 const teams=aulaTeams(),id=teams.some(t=>t.id===w5.team)?w5.team:teams[0].id,team=teams.find(t=>t.id===id),grades=p.aulaRubric?.[id]||[0,0,0,0],total=grades.reduce((n,v)=>n+Number(v),0);
 return aulaPanel(`<header class="aulaHead"><h2>Compartimos y evaluamos · 10 puntos</h2><p>«La necesidad es… El deseo es… El problema es… Aquí hay una oportunidad para…»</p></header><div class="aulaTeamPicker"><button class="action primary" data-aulatable="table">Tabla · Grupos 1 a 5 →</button><label>Equipo <select data-aulateam>${teams.map(t=>`<option value="${t.id}" ${id===t.id?'selected':''}>${w5Esc(t.name)}</option>`).join('')}</select></label><strong style="border-color:${team.color}">${w5Esc(team.name)} · ${total} / 10</strong></div><table class="aulaRubric"><thead><tr><th>Criterio</th><th>Qué observamos</th><th>Puntos</th></tr></thead><tbody>${aulaCriteria.map(([title,max,desc],i)=>`<tr><th>${title}</th><td>${desc}</td><td><select aria-label="${title}" data-aulascore="${i}" data-aulascoreteam="${id}">${Array.from({length:max*2+1},(_,n)=>n/2).map(n=>`<option value="${n}" ${Number(grades[i])===n?'selected':''}>${n}</option>`).join('')}</select> / ${max}</td></tr>`).join('')}</tbody></table><p class="aulaFeedback" role="status">Puntuación guardada para ${w5Esc(team.name)} · 4.º ${w5.course}. La docente asigna los puntos según la evidencia observada.</p>${aulaNav('<button class="action" data-wstep="2">← Actividad grupal</button>','<button class="action" data-deckcover>Volver a la portada</button>')}`);
};
w5Root.addEventListener('click',e=>{if(!aulaEnabled())return;const b=e.target.closest('button');if(!b)return;const d=b.dataset,p=w5Read();if(d.aulatable!==undefined){w5.aulaScoreView=d.aulatable;w5Render();}else if(d.aulaphase!==undefined){const s=p.aulaRoutine||{answers:{},ideas:{}};w5Save({aulaRoutine:{...s,phase:Number(d.aulaphase)}});w5Render();}else if(d.aulaanswer!==undefined){const s=p.aulaRoutine||{phase:0,answers:{},ideas:{}};w5Save({aulaRoutine:{...s,answers:{...s.answers,[s.phase||0]:Number(d.aulaanswer)}}});w5Render();}else if(d.aulacase!==undefined){w5.item=Number(d.aulacase);w5Render();}else if(d.aulaconcept!==undefined){const index=Number(d.aulaconcept),current=w5.aulaConceptIndex||0;if(index>current&&p.aulaClassify?.[current]!==aulaConcepts[current][0])return;w5.aulaConceptIndex=index;w5Render();}else if(d.aulaclass!==undefined){w5Save({aulaClassify:{...p.aulaClassify,[d.aulaclass]:d.aulakind}});w5Render();}});
w5Root.addEventListener('input',e=>{if(!aulaEnabled()||e.target.dataset.aulaidea===undefined)return;const s=w5Read().aulaRoutine||{phase:0,answers:{}};w5Save({aulaRoutine:{...s,ideas:{...s.ideas,[e.target.dataset.aulaidea]:e.target.value}}});});
w5Root.addEventListener('change',e=>{if(!aulaEnabled())return;const d=e.target.dataset;if(d.aulateam!==undefined){w5.team=Number(e.target.value);w5Render();}else if(d.aulascore!==undefined){const p=w5Read(),grades=[...(p.aulaRubric?.[d.aulascoreteam]||[0,0,0,0])];grades[Number(d.aulascore)]=Number(e.target.value);w5Save({aulaRubric:{...p.aulaRubric,[d.aulascoreteam]:grades}});w5Render();}});
const aulaOldPaginate=deckPaginate;
deckPaginate=function(){document.body.classList.toggle('deck-aula',aulaEnabled()&&!!w5Root.querySelector('.aulaPanel'));if(!document.body.classList.contains('deck-aula')){aulaOldPaginate();return;}deckState.pages=[];document.getElementById('deckPage').textContent=['Observamos','Pensamos','Analizamos','Evaluamos'][w5.step];for(const name of ['deckprev','decknext'])deckTools.querySelector(`[data-${name}]`).hidden=true;};
const aulaOldEnter=deckEnter;deckEnter=function(){for(const name of ['deckprev','decknext'])deckTools.querySelector(`[data-${name}]`).hidden=false;aulaOldEnter();};