
/* PDF export: print a private document generated in the browser. */
function saveTeamsPdf(){
 let grade=activeGrade===4?4:activeGrade,parallel=grade===4?course:(g57State.course||'A'),date=grade===4?document.getElementById('classDate').value:g57Storage().date,teams=[];
 if(grade===4){const state=s2State();if(!state)return;teams=Array.from({length:s2GroupCount(state)},(_,i)=>({name:state.names[i]||'',norm:state.norms[i]||'',members:s2Names().filter(n=>state.assignment[n]===i).map(name=>({name,role:state.roles[name]||'Por asignar'}))}));}
 else{const state=eqState();if(!state)return;teams=state.map(t=>({name:t.name||'',norm:t.norm||'',members:t.members.map(m=>({name:m.name,role:m.roles.join(' + ')||'Por asignar'}))}));}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const colors=['#ef8fba','#71c9e7','#ffd465','#83d9ad','#aa9cec','#edaa83'];
 const frame=document.createElement('iframe');frame.title='Documento de equipos para PDF';frame.style.cssText='position:fixed;width:1px;height:1px;left:-10000px;border:0';document.body.append(frame);
 const doc=frame.contentDocument;doc.open();doc.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Equipos ${grade} ${parallel} - Semana 4</title><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#17304c;margin:0}h1{font-size:22px;margin:0 0 5px}.meta{font-size:13px;margin:0 0 16px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.team{border:2px solid var(--color);border-radius:15px;padding:13px;break-inside:avoid;page-break-inside:avoid}h2{font-size:16px;margin:0 0 10px}.name,.norm{font-size:12px;margin:8px 0;line-height:1.4}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{font-size:12px;padding:8px 3px;text-align:left;border-bottom:1px solid #e0eaef;overflow-wrap:anywhere}th:first-child{width:55%}.norm{margin-top:12px}.empty{color:#61788a;font-size:12px}footer{font-size:10px;margin-top:14px;color:#647789}body{-webkit-print-color-adjust:exact;print-color-adjust:exact}</style></head><body><h1>EMPRENDIMIENTO · Equipos formados</h1><p class="meta">Curso: ${grade}.º ${esc(parallel)} · Semana 4 · Fecha: ${esc(date?new Date(date+'T12:00:00').toLocaleDateString('es-EC',{day:'numeric',month:'long',year:'numeric'}):'Por definir')}</p><div class="grid">${teams.map((t,i)=>`<section class="team" style="--color:${colors[i%6]}"><h2>Equipo ${i+1} · ${t.members.length} integrantes</h2><p class="name"><b>Nombre del equipo:</b> ${esc(t.name||'Por definir')}</p>${t.members.length?`<table><thead><tr><th>Estudiante</th><th>Rol</th></tr></thead><tbody>${t.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.role)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">Sin integrantes</p>'}<p class="norm"><b>Una norma para colaborar:</b><br>${esc(t.norm||'Por definir')}</p></section>`).join('')}</div><footer>Lcda. Anita Parreño · Organización de equipos</footer></body></html>`);doc.close();
 const win=frame.contentWindow;win.addEventListener('afterprint',()=>frame.remove(),{once:true});win.focus();win.print();
}
document.addEventListener('click',e=>{if(e.target.closest('[data-save-teams-pdf]'))saveTeamsPdf()});
