/* Organización de equipos: semana 4, sesión 1. Las listas permanecen locales. */
for(const grade of [5,7]){g57Data[grade].title='Creamos nuestro equipo emprendedor';g57Data[grade].objective='Organizar equipos, reconocer los talentos de sus integrantes y distribuir roles para trabajar juntos en un reto emprendedor.';g57Data[grade].minutes=[4,5,16,5]}
const eqRoles=['Líder','Secretario/a','Investigador/a','Diseñador/a','Expositor/a'];
const eqColors=['#10b7d0','#ea6fa0','#e9ab24','#42b784','#9569cd','#ed8055'];
const eqIcons=['🌊','🌸','☀️','🌿','🔮','🔥'];
const eqCourse=()=>`${activeGrade}${g57State.course||'A'}`;
const eqRoster=()=>{try{return JSON.parse(localStorage.getItem('eq57-listas')||'{}')[eqCourse()]||[]}catch{return []}};
const eqState=()=>g57Storage().teams;
const eqSave=s=>g57Save({teams:s});
const eqEarned=t=>t.members.length>0&&t.name.trim()&&t.norm.trim()&&t.members.every(m=>m.roles.length)&&new Set(t.members.flatMap(m=>m.roles)).size===5;
function eqCreate(){let list=[...eqRoster()];for(let i=list.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}let count=Math.min(Number(document.getElementById('eqCount')?.value||6),list.length);let teams=Array.from({length:count},()=>({name:'',norm:'',members:[]}));list.forEach((name,i)=>teams[i%count].members.push({name,roles:[],talent:''}));eqSave(teams);renderG57()}
function eqBoard(){let list=eqRoster(),teams=eqState();if(!list.length)return `<div class="rosterLoader"><h3>📋 Carga las listas de quinto y séptimo</h3><p>Selecciona el archivo <b>listas-privadas-quinto-septimo.json</b> que acompaña esta actualización. Solo debes cargarlo una vez en cada navegador.</p><input type="file" id="eqImport" accept=".json,application/json"><p id="eqMessage" role="status">Cada paralelo abrirá su propia lista.</p></div>`;return `<div class="eqTools"><b>${activeGrade}.º ${g57State.course||'A'} · ${list.length} estudiantes</b><label>Número de grupos <select id="eqCount">${[2,3,4,5,6].map(n=>`<option value="${n}" ${n===(teams?.length||6)?'selected':''}>${n} grupos</option>`).join('')}</select></label><button class="g57Button" data-eq-create>${teams?'↻ Volver a repartir':'🎨 Repartir colores y formar grupos'}</button></div><p class="g57Small">Busca tu color y reúne a tu equipo. La nueva distribución reinicia los acuerdos y los roles.</p>${teams?`<div class="teamsGrid">${teams.map((t,i)=>`<article class="teamCard" style="--team:${eqColors[i]}"><h3>${eqIcons[i]} Grupo ${i+1} · ${t.members.length} integrantes</h3><label>Nombre del equipo<input data-eq-field="name" data-eq-team="${i}" value="${g57Esc(t.name)}" placeholder="Inventen un nombre"></label>${t.members.map((m,j)=>`<div class="eqMember"><b>${g57Esc(m.name)}</b><label>Mi talento<input data-eq-field="talent" data-eq-team="${i}" data-eq-member="${j}" value="${g57Esc(m.talent)}" placeholder="¿Qué aporto?"></label><label>Cambiar de grupo<select data-eq-move="${j}" data-eq-team="${i}">${teams.map((_,k)=>`<option value="${k}" ${k===i?'selected':''}>Grupo ${k+1}</option>`).join('')}</select></label><div class="eqRoleChecks">${eqRoles.map(role=>`<label><input type="checkbox" data-eq-role="${role}" data-eq-team="${i}" data-eq-member="${j}" ${m.roles.includes(role)?'checked':''}> ${role}</label>`).join('')}</div></div>`).join('')}<label>Acuerdo de colaboración<input data-eq-field="norm" data-eq-team="${i}" value="${g57Esc(t.norm)}" placeholder="Escuchamos y participamos por turnos"></label><div class="teamBadge ${eqEarned(t)?'earned':''}">${eqEarned(t)?'🏅 Insignia: Equipo emprendedor listo':'☆ Nombre + acuerdo + todos participan + cinco roles cubiertos'}</div></article>`).join('')}</div>`:''}`}
function eqLesson(step){let p=g57Storage();if(step===0)return `<span class="g57Badge">4 min · Espejos en pareja</span><h2>Conectamos sin palabras</h2><div class="g57Visual"><div class="g57Scene"><span>🙋</span><span>🪞</span><span>🙋</span><small>Una persona guía y la otra imita.</small></div><div><p class="g57Statement">Haz un movimiento lento. Tu compañero lo refleja.</p><p class="g57Intro">1. Frente a frente, sin tocarse.<br>2. Una persona guía durante 30 segundos.<br>3. Cambien de guía.<br>4. Intenten coordinarse sin hablar.</p></div></div><div class="g57Feedback">¿Qué nos ayudó a coordinarnos? Escuchar, observar y respetar el ritmo también cuentan en un equipo.</div>`;
if(step===1)return `<span class="g57Badge">5 min · Pienso · Comparto · Elijo</span><h2>Mi talento tiene una misión</h2><p class="g57Intro">Piensa en algo que haces bien. Compártelo con una pareja y elige un rol donde podrías aportar. Los roles se pueden aprender y cambiar.</p><div class="g57Ideas">${[['🧭','Líder','Organiza los turnos y ayuda a llegar a acuerdos.'],['✍️','Secretario/a','Registra ideas y acuerdos en Pages.'],['🔎','Investigador/a','Busca información y comprueba lo que falta saber.'],['🎨','Diseñador/a','Organiza dibujos, imágenes y la presentación visual.'],['🎤','Expositor/a','Explica el trabajo y escucha preguntas.']].map(([icon,role,text])=>`<button data-eq-example="${role}" class="${p.roleExample===role?'active':''}"><span style="font-size:2.7rem;display:block">${icon}</span><b>${role}</b><p>${text}</p></button>`).join('')}</div>${p.roleExample?`<div class="g57Feedback">Elegimos ${g57Esc(p.roleExample)}. ¿Qué talento necesita? ¿Quién quiere practicarlo hoy?</div>`:''}`;
if(step===2)return `<span class="g57Badge">16 min · Misión de equipo</span><h2>Encuentra tu color, crea tu equipo</h2><p class="g57Intro">Reúnete con tu grupo, compartan sus talentos, asignen los cinco roles y escriban un acuerdo. ¡Ganen su insignia!</p><p class="note">Si hay menos de cinco integrantes, una persona puede asumir dos roles. Todos deben tener una responsabilidad.</p>${eqBoard()}`;
let teams=eqState();return `<span class="g57Badge">5 min · Presentamos nuestro equipo</span><h2>¡Nuestro equipo está listo!</h2><p class="g57Intro">En 30 segundos, cada grupo presenta su nombre, cómo aportará cada integrante y su acuerdo. Guarden una captura en el portafolio de Pages.</p>${teams?`<div class="teamsGrid">${teams.map((t,i)=>`<article class="teamCard" style="--team:${eqColors[i]}"><h3>${eqIcons[i]} Grupo ${i+1} · ${g57Esc(t.name||'Elijan un nombre')}</h3>${t.members.map(m=>`<p><b>${g57Esc(m.name)}</b> · ${g57Esc(m.roles.join(' + ')||'Rol pendiente')}${m.talent?' · '+g57Esc(m.talent):''}</p>`).join('')}<p><b>Acuerdo:</b> ${g57Esc(t.norm||'Por definir')}</p><div class="teamBadge ${eqEarned(t)?'earned':''}">${eqEarned(t)?'🏅 Equipo emprendedor listo':'☆ Completen su misión en el momento anterior'}</div><button class="g57Button" data-eq-download="${i}">Guardar tarjeta del equipo</button></article>`).join('')}</div>`:'<div class="g57Feedback">Formen primero los grupos en la misión anterior.</div>'}<div class="g57Problem">«Somos ___; nuestros talentos son ___; nos comprometemos a ___».</div>`}
g57Fifth=eqLesson;g57Seventh=eqLesson;
function eqDownload(i){let t=eqState()[i],c=document.createElement('canvas');c.width=1500;c.height=350+t.members.length*120;let x=c.getContext('2d');x.fillStyle=eqColors[i];x.fillRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(22,22,c.width-44,c.height-44);x.fillStyle='#17304c';x.font='bold 46px system-ui';x.fillText(`Grupo ${i+1} · ${t.name||'Equipo emprendedor'}`,60,100);x.font='28px system-ui';x.fillText(`${activeGrade}.º ${g57State.course||'A'} · Semana 4 · ${g57Date(g57Storage().date)}`,60,155);let y=220;t.members.forEach(m=>{x.font='bold 31px system-ui';x.fillText(m.name,60,y);x.font='26px system-ui';x.fillText(m.roles.join(' + ')||'Rol pendiente',60,y+38);x.fillText('Talento: '+(m.talent||'Por compartir'),60,y+72);y+=120});x.font='27px system-ui';x.fillText('Acuerdo: '+t.norm,60,y+25);x.fillText(eqEarned(t)?'★ Equipo emprendedor listo':'Completen los acuerdos y roles',60,y+80);g57Download(c.toDataURL(),'equipo-'+eqCourse()+'-'+(i+1)+'.png')}
g57Root().addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.eqCreate!==undefined)eqCreate();if(b.dataset.eqExample){g57Save({roleExample:b.dataset.eqExample});renderG57()}if(b.dataset.eqDownload!==undefined)eqDownload(Number(b.dataset.eqDownload))});
g57Root().addEventListener('change',async e=>{let el=e.target;if(el.id==='eqImport'){try{let data=JSON.parse(await el.files[0].text());for(let key of ['5A','5B','5C','7A','7B','7C']){if(!Array.isArray(data[key])||data[key].some(n=>typeof n!=='string'||!n.trim())||new Set(data[key]).size!==data[key].length)throw Error('Lista no válida: '+key)}localStorage.setItem('eq57-listas',JSON.stringify(data));renderG57()}catch(err){document.getElementById('eqMessage').textContent='No se pudo cargar: '+err.message}return}let d=el.dataset;if(d.eqTeam===undefined)return;let teams=eqState(),i=Number(d.eqTeam),j=Number(d.eqMember);if(d.eqField){if(d.eqField==='talent')teams[i].members[j].talent=el.value;else teams[i][d.eqField]=el.value}if(d.eqRole){let roles=teams[i].members[j].roles;teams[i].members[j].roles=el.checked?[...new Set([...roles,d.eqRole])]:roles.filter(r=>r!==d.eqRole)}if(d.eqMove!==undefined){let target=Number(el.value);if(target!==i){let m=teams[i].members.splice(Number(d.eqMove),1)[0];teams[target].members.push(m)}}eqSave(teams);renderG57()});
