/* Organización de equipos: semana 4, sesión 1. Las listas permanecen locales. */
for(const grade of [5,6,7]){g57Data[grade].title='Creamos nuestro equipo emprendedor';g57Data[grade].objective='Organizar equipos, reconocer los talentos de sus integrantes y distribuir roles para trabajar juntos en un reto emprendedor.';g57Data[grade].minutes=[4,5,16,5]}
const eqRoles=['Líder','Secretario/a','Investigador/a','Diseñador/a','Expositor/a'];
const eqColors=['#ef8fba','#71c9e7','#ffd465','#83d9ad','#aa9cec','#edaa83'];
const eqIcons=['🌊','🌸','☀️','🌿','🔮','🔥'];
const eqCourse=()=>`${activeGrade}${g57State.course||'A'}`;
const eqAllowed=(name,key=eqCourse())=>key!=='6A'||name.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()!=='cabrera camila';
const eqRoster=()=>{try{return (JSON.parse(localStorage.getItem('eq57-listas')||'{}')[eqCourse()]||[]).filter(n=>eqAllowed(n))}catch{return []}};
const eqState=()=>{const teams=g57Storage().teams;if(!teams)return teams;return teams.map(t=>({...t,members:t.members.filter(m=>eqAllowed(m.name))}))};
const eqSave=s=>g57Save({teams:s});
const eqEarned=t=>t.members.length>0&&t.name.trim()&&t.norm.trim()&&t.members.every(m=>m.roles.length)&&new Set(t.members.flatMap(m=>m.roles)).size===5;
function eqCreate(){let list=eqRoster().filter(n=>!(g57Storage().excluded||[]).includes(n));if(!list.length)return;for(let i=list.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}let count=Math.min(Number(document.getElementById('eqCount')?.value||6),list.length);let teams=Array.from({length:count},()=>({name:'',norm:'',members:[]}));list.forEach((name,i)=>teams[i%count].members.push({name,roles:[],talent:''}));eqSave(teams);renderG57()}

function eqSimpleCard(t,i,editing=false){const teams=eqState()||[];return `<article class="teamCard" style="--team:${eqColors[i]}"><h3>Equipo ${i+1} · ${t.members.length} integrantes</h3>${editing?`<label>Nombre del equipo<input data-eq-field="name" data-eq-team="${i}" value="${g57Esc(t.name||'')}" placeholder="Escribe el nombre"></label>`:`<p><b>Nombre del equipo:</b> ${g57Esc(t.name||'Por definir')}</p>`}${t.members.map((m,j)=>`<div class="memberRow"><b>${g57Esc(m.name)}</b>${editing?`<div><select data-eq-role-select="${j}" data-eq-team="${i}" aria-label="Rol de ${g57Esc(m.name)}"><option value="">Elige un rol</option>${eqRoleOptions(m.roles).map(roles=>`<option value="${g57Esc(roles.join('|'))}" ${roles.join('|')===m.roles.join('|')?'selected':''}>${g57Esc(roles.join(' + '))}</option>`).join('')}</select><select data-eq-move="${j}" data-eq-team="${i}" aria-label="Equipo de ${g57Esc(m.name)}">${Array.from({length:6},(_,k)=>`<option value="${k}" ${k===i?'selected':''}>Equipo ${k+1}</option>`).join('')}</select></div>`:`<span>${g57Esc(m.roles.join(' + ')||'Rol pendiente')}</span>`}</div>`).join('')}${editing?`<label>Una norma para colaborar<input data-eq-field="norm" data-eq-team="${i}" value="${g57Esc(t.norm||'')}" placeholder="Ejemplo: escuchamos por turnos"></label>`:`<p><b>Una norma para colaborar:</b> ${g57Esc(t.norm||'Por definir')}</p>`}<div class="teamBadge ${eqEarned(t)?'earned':''}">${eqEarned(t)?'🏅 Insignia ganada: Equipo listo':'☆ Completen los roles, el nombre y la norma'}</div></article>`}

function eqRoleOptions(current){let options=eqRoles.map(r=>[r]);for(let i=0;i<eqRoles.length;i++)for(let j=i+1;j<eqRoles.length;j++)options.push([eqRoles[i],eqRoles[j]]);if(current.length&&!options.some(r=>r.join('|')===current.join('|')))options.push(current);return options}

function eqBoard(){let list=eqRoster(),teams=eqState();if(!list.length)return `<div class="rosterLoader"><h3>📋 Carga las listas de quinto a séptimo</h3><p>Selecciona el Excel <b>CALIFICACIONES Y ASISTENCIAS EMPRENDIMIENTO.xlsx</b> o el archivo privado JSON. Solo debes cargarlo una vez en cada navegador.</p><input type="file" id="eqImport" accept=".json,.xlsx,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><p id="eqMessage" role="status">Cada paralelo abrirá su lista; revisa los participantes antes de repartir grupos.</p></div>`;return `<div class="eqTools"><b>${activeGrade}.º ${g57State.course||'A'} · ${list.length} estudiantes</b><label>Número de grupos <select id="eqCount">${[2,3,4,5,6].map(n=>`<option value="${n}" ${n===(teams?.length||6)?'selected':''}>${n} grupos</option>`).join('')}</select></label><button class="g57Button" data-eq-create>${teams?'↻ Volver a repartir':'🎨 Repartir colores y formar grupos'}</button></div><details class="teacher"><summary>Revisar participantes (${list.filter(n=>!(g57Storage().excluded||[]).includes(n)).length} seleccionados)</summary><p>Desmarca a quienes no participarán. Si modificas esta selección, vuelve a repartir los grupos.</p><div class="eqRoleChecks">${list.map(n=>`<label><input type="checkbox" data-eq-participant="${g57Esc(n)}" ${(g57Storage().excluded||[]).includes(n)?'':'checked'}> ${g57Esc(n)}</label>`).join('')}</div><input type="file" id="eqImport" accept=".json,.xlsx"></details><p class="g57Small">Busca tu color y reúne a tu equipo. La nueva distribución reinicia los roles.</p>${teams?`<div class="teamsGrid">${teams.map((t,i)=>eqSimpleCard(t,i,true)).join('')}</div>`:''}`}

function eqLesson(step){let p=g57Storage();if(step===0)return `<span class="g57Badge">4 min · Espejos en pareja</span><h2>Conectamos sin palabras</h2><div class="g57Visual"><div class="g57Scene"><span>🙋</span><span>🪞</span><span>🙋</span><small>Una persona guía y la otra imita.</small></div><div><p class="g57Statement">Haz un movimiento lento. Tu compañero lo refleja.</p><p class="g57Intro">1. Frente a frente, sin tocarse.<br>2. Una persona guía durante 30 segundos.<br>3. Cambien de guía.<br>4. Intenten coordinarse sin hablar.</p></div></div><div class="g57Feedback">¿Qué nos ayudó a coordinarnos? Escuchar, observar y respetar el ritmo también cuentan en un equipo.</div>`;
if(step===1)return `<span class="g57Badge">5 min · Pienso · Comparto · Elijo</span><h2>Mi talento tiene una misión</h2><p class="g57Intro">Piensa en algo que haces bien. Compártelo con una pareja y elige un rol donde podrías aportar. Los roles se pueden aprender y cambiar.</p><div class="g57Ideas">${[['🧭','Líder','Organiza los turnos y ayuda a llegar a acuerdos.'],['✍️','Secretario/a','Registra ideas y acuerdos en Pages.'],['🔎','Investigador/a','Busca información y comprueba lo que falta saber.'],['🎨','Diseñador/a','Organiza dibujos, imágenes y la presentación visual.'],['🎤','Expositor/a','Explica el trabajo y escucha preguntas.']].map(([icon,role,text])=>`<button data-eq-example="${role}" class="${p.roleExample===role?'active':''}"><span style="font-size:2.7rem;display:block">${icon}</span><b>${role}</b><p>${text}</p></button>`).join('')}</div>${p.roleExample?`<div class="g57Feedback">Elegimos ${g57Esc(p.roleExample)}. ¿Qué talento necesita? ¿Quién quiere practicarlo hoy?</div>`:''}`;
if(step===2)return `<span class="g57Badge">16 min · Misión de equipo</span><h2>Encuentra tu color, crea tu equipo</h2><p class="g57Intro">Reúnete con tu grupo, elijan el nombre del equipo, asignen los roles y escriban una norma para colaborar.</p><p class="note">Si hay menos de cinco integrantes, una persona puede asumir dos roles. Todos deben tener una responsabilidad.</p>${eqBoard()}`;
let teams=eqState();return `<span class="g57Badge">5 min · Presentamos nuestro equipo</span><h2>¡Nuestro equipo está listo!</h2><p class="g57Intro">En 30 segundos, cada equipo presenta su nombre, sus integrantes, los roles y su norma. Guarden la tarjeta en Pages.</p>${teams?`<div class="teamsGrid">${teams.map((t,i)=>`<div>${eqSimpleCard(t,i)}<button class="g57Button" data-eq-download="${i}" style="margin:10px 0">Guardar grupo ${i+1}</button></div>`).join('')}</div>`:'<div class="g57Feedback">Formen primero los grupos en la misión anterior.</div>'}`}

g57Fifth=eqLesson;g57Seventh=eqLesson;
function eqDownload(i){let t=eqState()[i],c=document.createElement('canvas');c.width=1500;c.height=220+t.members.length*105;let x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.strokeStyle=eqColors[i];x.lineWidth=12;x.strokeRect(15,15,c.width-30,c.height-30);x.fillStyle='#17304c';x.font='bold 48px system-ui';x.fillText('GRUPO '+(i+1),65,95);x.font='bold 30px system-ui';x.fillText('Estudiante',65,165);x.fillText('Rol',660,165);let y=240;t.members.forEach(m=>{x.font='bold 32px system-ui';x.fillText(m.name,65,y);x.font='28px system-ui';x.fillText(m.roles.join(' + ')||'Por asignar',660,y,760);y+=105});g57Download(c.toDataURL(),'grupo-'+eqCourse()+'-'+(i+1)+'.png')}

g57Root().addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.eqCreate!==undefined)eqCreate();if(b.dataset.eqExample){g57Save({roleExample:b.dataset.eqExample});renderG57()}if(b.dataset.eqDownload!==undefined)eqDownload(Number(b.dataset.eqDownload))});
g57Root().addEventListener('change',async e=>{let el=e.target;if(el.id==='eqImport'){try{let file=el.files[0];if(!file)return;let data=/\.xlsx$/i.test(file.name)?await eqParseWorkbook(file):JSON.parse(await file.text());for(let [key,names] of Object.entries(data)){if(!/^[567][ABC]$/.test(key)||!Array.isArray(names)||!names.length||names.some(n=>typeof n!=='string'||!n.trim())||new Set(names).size!==names.length)throw Error('Lista no válida: '+key)}if(!data[eqCourse()])throw Error('Falta la lista '+eqCourse());let previous=JSON.parse(localStorage.getItem('eq57-listas')||'{}');localStorage.setItem('eq57-listas',JSON.stringify({...previous,...data}));g57Save({teams:null,excluded:[]});renderG57()}catch(err){let msg=document.getElementById('eqMessage');if(msg)msg.textContent='No se pudo cargar: '+err.message;else alert('No se pudo cargar: '+err.message)}return}let d=el.dataset;if(d.eqParticipant){let excluded=g57Storage().excluded||[];g57Save({excluded:el.checked?excluded.filter(n=>n!==d.eqParticipant):[...new Set([...excluded,d.eqParticipant])],teams:null});renderG57();return}if(d.eqTeam===undefined)return;let teams=eqState(),i=Number(d.eqTeam),j=Number(d.eqMember);if(d.eqField){if(d.eqField==='talent')teams[i].members[j].talent=el.value;else teams[i][d.eqField]=el.value}if(d.eqRoleSelect!==undefined){teams[i].members[Number(d.eqRoleSelect)].roles=el.value?el.value.split('|'):[]}if(d.eqRole){let roles=teams[i].members[j].roles;teams[i].members[j].roles=el.checked?[...new Set([...roles,d.eqRole])]:roles.filter(r=>r!==d.eqRole)}if(d.eqMove!==undefined){let target=Number(el.value);if(target!==i){while(teams.length<=target)teams.push({name:'',norm:'',members:[]});let m=teams[i].members.splice(Number(d.eqMove),1)[0];teams[target].members.push(m)}}eqSave(teams);renderG57()});

/* Read only: local XLSX ZIP + XML, without uploading names. */
async function eqParseWorkbook(file){
 const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer),decoder=new TextDecoder(),entries={};let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break}
 if(end<0)throw Error('El archivo no es un Excel XLSX válido.');
 let pos=view.getUint32(end+16,true),count=view.getUint16(end+10,true);
 for(let i=0;i<count;i++){if(view.getUint32(pos,true)!==0x02014b50)throw Error('No se pudo leer el índice del Excel.');let method=view.getUint16(pos+10,true),size=view.getUint32(pos+20,true),nl=view.getUint16(pos+28,true),ex=view.getUint16(pos+30,true),cl=view.getUint16(pos+32,true),offset=view.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+nl));entries[name]={method,size,offset};pos+=46+nl+ex+cl}
 async function xml(name){let e=entries[name];if(!e)throw Error('Falta '+name);let p=e.offset,nl=view.getUint16(p+26,true),ex=view.getUint16(p+28,true),data=bytes.slice(p+30+nl+ex,p+30+nl+ex+e.size);if(e.method===8){if(typeof DecompressionStream==='undefined')throw Error('Este navegador no puede abrir XLSX; utiliza el archivo JSON.');try{data=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer())}catch{throw Error('Utiliza Chrome actualizado para cargar el Excel.')}}else if(e.method!==0)throw Error('Compresión del Excel no compatible.');let doc=new DOMParser().parseFromString(decoder.decode(data),'application/xml');if(doc.querySelector('parsererror'))throw Error('XML del Excel inválido.');return doc}
 let shared=entries['xl/sharedStrings.xml']?Array.from((await xml('xl/sharedStrings.xml')).getElementsByTagName('si'),n=>n.textContent):[];
 let workbook=await xml('xl/workbook.xml'),rels=await xml('xl/_rels/workbook.xml.rels'),links={};for(let r of rels.getElementsByTagName('Relationship'))links[r.getAttribute('Id')]=r.getAttribute('Target');
 let result={};for(let sheet of workbook.getElementsByTagName('sheet')){let name=sheet.getAttribute('name'),m=name.match(/^(QUINTO|SEXTO|SÉPTIMO) ([ABC])$/);if(!m)continue;let key=({'QUINTO':5,'SEXTO':6,'SÉPTIMO':7}[m[1]])+m[2],target=links[sheet.getAttribute('r:id')],path=target.startsWith('/')?target.slice(1):'xl/'+target,doc=await xml(path),names=[];
 for(let row of doc.getElementsByTagName('row')){if(Number(row.getAttribute('r'))<10)continue;let cells={};for(let c of row.getElementsByTagName('c')){let col=c.getAttribute('r').replace(/[0-9]/g,''),v=c.getElementsByTagName('v')[0],type=c.getAttribute('t');cells[col]=type==='s'?shared[Number(v?.textContent)]:type==='inlineStr'?c.getElementsByTagName('is')[0]?.textContent:v?.textContent}let full=cells.B?.trim();if(!full||(!/^\d+(\.0+)?$/.test(cells.A||'')&&cells.A))continue;let p=full.split(/\s+/),short;if(p.length===2)short=/^(KATHRYN|Isabela)$/i.test(p[0])?p[1]+' '+p[0]:full;else if(/^La Rosa /i.test(full))short='La Rosa '+p[3];else if(/^Paz y Miño /i.test(full))short='Paz y Miño '+p[4];else short=p[0]+' '+p[2];names.push(short.toLocaleLowerCase('es').replace(/(^|\s)\S/g,c=>c.toLocaleUpperCase('es')))}
 result[key]=names.filter(n=>eqAllowed(n,key))}
 return result
}
