/* Semana 4, sesión 1: experiencias guiadas de 5.º y 7.º. */
const g57Data={
  5:{title:'Empatizar y definir un problema real',objective:'Comprender cómo observar y escuchar a un usuario para reconocer necesidades reales y convertirlas en un problema claro.',minutes:[4,5,16,5],case:'Durante el recreo, una estudiante mira los carteles del patio, pregunta tres veces dónde entregar una botella y termina guardándola en su mochila.',user:'Una estudiante que quiere desechar una botella en el recreo',need:'saber dónde entregarla',evidence:'preguntó tres veces y guardó la botella',quiz:[
    {text:'La estudiante preguntó tres veces dónde entregar su botella.',answer:'Hecho',why:'Es una acción que se puede observar o escuchar.'},
    {text:'La estudiante es desordenada.',answer:'Suposición',why:'No sabemos eso a partir de lo observado.'},
    {text:'Guardó la botella en su mochila.',answer:'Hecho',why:'Es una conducta observable.'},
    {text:'No le importa cuidar el ambiente.',answer:'Suposición',why:'Es una interpretación sin evidencia.'},
    {text:'Los carteles están en el patio.',answer:'Hecho',why:'Es un detalle visible de la situación.'},
    {text:'Una aplicación resolvería el problema.',answer:'Suposición',why:'Es una solución adelantada; aún falta escuchar a la usuaria.'}
  ]},
  7:{title:'Piensa como un emprendedor de Silicon Valley',objective:'Aplicar pensamiento emprendedor para observar el entorno, identificar oportunidades y priorizar problemas con potencial de solución.',minutes:[4,5,16,5],cases:[
    {icon:'🚰',title:'Agua en el suelo',obs:'Durante tres recreos hubo agua junto al grifo; estudiantes rodearon la zona.',user:'Estudiantes que usan el patio',friction:'el piso mojado dificulta el paso',evidence:'observación en tres recreos',impact:'Alto'},
    {icon:'📚',title:'Fila en biblioteca',obs:'Al devolver libros, varias personas esperaron más de diez minutos.',user:'Estudiantes que devuelven libros',friction:'la devolución tarda',evidence:'tiempo de espera observado',impact:'Medio'},
    {icon:'🍎',title:'Comida desperdiciada',obs:'Al terminar el almuerzo, se encontraron varias frutas enteras en el basurero.',user:'Estudiantes del comedor',friction:'hay alimentos que se desechan sin consumir',evidence:'frutas enteras observadas',impact:'Alto'}
  ],sort:[
    {text:'«La fila duró 12 minutos y afectó a ocho estudiantes».',answer:'Problema',why:'Describe a quién afecta y una fricción medible.'},
    {text:'«La fila llega hasta la puerta».',answer:'Síntoma',why:'Es una señal observable; debemos investigar qué causa la demora.'},
    {text:'«Odio esperar; qué aburrido».',answer:'Queja',why:'Expresa una opinión sin definir usuario, contexto ni evidencia.'},
    {text:'«Se desecharon frutas enteras tres días seguidos».',answer:'Problema',why:'Hay una situación repetida que se puede investigar.'}
  ]}
};
const g57State={step:0,case:0,quiz:0,answers:{},ink:'#17304c',erase:false};
const g57Root=()=>document.getElementById('otherGradeContent');
const g57Key=()=>`emprendimiento-g57-${activeGrade}-${g57State.course||'A'}-s1`;
const g57Storage=()=>{try{return JSON.parse(localStorage.getItem(g57Key())||'{}')}catch{return {}}};
const g57Save=(patch)=>{try{localStorage.setItem(g57Key(),JSON.stringify({...g57Storage(),...patch}))}catch{}};
const g57Esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const g57Date=s=>s?new Date(`${s}T12:00:00`).toLocaleDateString('es-EC',{day:'numeric',month:'long',year:'numeric'}):'Selecciona la fecha de clase';
function renderG57(){
 const d=g57Data[activeGrade],p=g57Storage(),s=g57State.step;
 g57Root().innerHTML=`<div class="g57Controls"><span class="badge">Curso</span>${['A','B','C'].map(c=>`<button data-g57-course="${c}" class="${(g57State.course||'A')===c?'active':''}">${activeGrade}.º ${c}</button>`).join('')}<span class="badge">Sesión 1</span><label>Fecha <input id="g57Date" type="date" value="${p.date||''}"></label><button data-g57-complete class="${p.complete?'active':''}">${p.complete?'✓ Completada':'○ Pendiente'}</button></div>
 <section class="hero g57Hero"><div class="eyebrow g57Date">Fecha de la clase: ${g57Date(p.date)}</div><div class="weekRange">Semana 4 · 28 de septiembre al 2 de octubre de 2026 · ${activeGrade}.º ${g57State.course||'A'}</div><h1><span class="heroLabel">Tema:</span> ${d.title}</h1><p><b>Objetivo:</b> ${d.objective}</p></section>
 <nav class="g57Nav" aria-label="Momentos de la sesión">${['⚡ Activación','💭 Anticipación','🔎 Construcción','✍️ Consolidación'].map((name,i)=>`<button data-g57-step="${i}" class="${i===s?'active':''}" ${i===s?'aria-current="step"':''}>${name} · ${d.minutes[i]} min</button>`).join('')}</nav>
 <section class="g57Card" id="g57Stage" aria-live="polite">${activeGrade===5?g57Fifth(s):g57Seventh(s)}</section>
 <div class="g57Footer"><button class="g57Button" data-g57-prev ${s===0?'disabled':''}>← Anterior</button><span class="g57Counter">${s+1} de 4</span><button class="g57Button" data-g57-next ${s===3?'disabled':''}>Siguiente →</button></div>
 <details class="g57Notes"><summary>Guía docente · materiales y tiempo</summary><p>${activeGrade===5?'Proyector, iPad, fotografía o escena escolar, pizarra y Pages para una nota breve. Preguntar «¿qué observaste?» antes de «¿qué piensas?». La escucha directa al usuario permite confirmar las necesidades.':'Proyector, iPad y escenas escolares. Observar primero; preguntar a las personas afectadas y comprobar frecuencia e impacto antes de diseñar soluciones. El desafío de 12 palabras sirve como evidencia de salida.'}</p></details><p class="footer">Fecha, avance y respuestas se guardan en este navegador para cada paralelo.</p>`;
 if(activeGrade===5&&s===1)g57CanvasInit();
}
function g57Fifth(s){const d=g57Data[5],p=g57Storage();
 if(s===0)return `<span class="g57Badge">4 min · Emoji humano</span><h2>¿Cómo se sentiría?</h2><p class="g57Intro">Representa con tu cara y tu cuerpo la emoción de alguien que espera mucho, pierde un objeto o no entiende una instrucción. La clase adivina la situación.</p><div class="g57Visual"><div class="g57Scene"><span>🕒</span><span>😕</span><small>Espera para entregar algo</small></div><div><p class="g57Statement">Elige una situación y muestra la emoción sin hablar.</p><div class="g57Ideas">${['🕒 Esperar mucho','🔎 Perder algo','❔ No entender una instrucción'].map((x,i)=>`<button data-g57-emotion="${i}" class="${p.emotion===i?'active':''}">${x}</button>`).join('')}</div></div></div>${p.emotion!==undefined?`<div class="g57Feedback">Ahora pregunta: «¿Cómo te sentirías? ¿Qué necesitarías saber?». Una emoción nos da una pista; todavía debemos escuchar a la persona.</div>`:''}`;
 if(s===1)return `<span class="g57Badge">5 min · Rutina de pensamiento</span><h2>Veo · Pienso · Me pregunto</h2><p class="g57Intro">Observa esta escena escolar. ¿Qué puedes ver de verdad y qué estás suponiendo? Escribe o dibuja con el Apple Pencil sobre la pizarra.</p><div class="g57Visual"><div class="g57Scene"><span>👧</span><span>♻️</span><span>❔</span><small>Una estudiante busca dónde entregar su botella.</small></div><div class="g57Ideas"><article>👁️ <b>Veo</b><br>Un hecho visible</article><article>💭 <b>Pienso</b><br>Una posible explicación</article><article>❓ <b>Me pregunto</b><br>Algo que debo comprobar</article></div></div><div class="g57Tools"><button data-g57-ink="#17304c" class="active">Azul</button><button data-g57-ink="#e34c83">Rosa</button><button data-g57-ink="#0a987c">Verde</button><button data-g57-erase>Borrar con el lápiz</button><button data-g57-undo>Deshacer</button><button data-g57-clear>Limpiar</button><button data-g57-download>Guardar imagen</button></div><canvas id="g57Canvas" class="g57Canvas" aria-label="Pizarra para dibujar o escribir con mouse o Apple Pencil"></canvas><p class="g57Small">Pregunta para la clase: «¿Qué le preguntaríamos a la estudiante para saber qué necesita?»</p>`;
 if(s===2){let c=g57State.case;return `<span class="g57Badge">16 min · Modelado de empatía</span><h2>Detectives de necesidades</h2><p class="g57Intro">Caso: ${d.case}</p><div class="g57Map">${[['👤','Usuario'],['👀','Qué hace'],['💛','Qué siente'],['🧩','Qué necesita'],['❓','Qué falta saber']].map((x,i)=>`<div class="${c>=i?'lit':''}"><strong>${x[0]}</strong>${x[1]}</div>`).join('')}</div><div class="g57Case"><h3>${['1. ¿A quién observamos?','2. ¿Qué hizo realmente?','3. ¿Cómo podría sentirse?','4. ¿Qué podría necesitar?','5. ¿Qué falta comprobar?','6. Definimos el problema'][c]}</h3><p class="g57Statement">${['Una estudiante que intenta entregar una botella.','Miró los carteles, preguntó tres veces y guardó la botella.','Quizá está confundida. Es una hipótesis, no un hecho.','Necesita saber dónde entregar la botella. Debemos escucharlo de ella.','Preguntarle: «¿Qué buscabas? ¿Qué parte fue difícil?».','La estudiante necesita saber dónde entregar su botella porque preguntó tres veces y acabó guardándola.'][c]}</p><p class="g57Small">${c===5?'La frase nombra usuario, necesidad y evidencia. Aún no propone una solución.':'La docente revela un paso; el grupo aporta una observación o pregunta.'}</p></div><div class="g57Footer"><button class="g57Button" data-g57-case-prev ${c===0?'disabled':''}>← Paso anterior</button><span class="g57Counter">${c+1} / 6</span><button class="g57Button" data-g57-case-next ${c===5?'disabled':''}>Revelar siguiente →</button></div>`}
 let q=g57State.quiz,item=d.quiz[q],a=g57State.answers[q];return `<span class="g57Badge">5 min · Hecho o suposición</span><h2>¿Qué sabemos de verdad?</h2><p class="g57Intro">Vota con la clase. Justifiquen una respuesta y escriban en Pages una idea que descubrieron hoy.</p><div class="g57Step"><span class="g57Counter">Afirmación ${q+1} / 6</span><p class="g57Statement">${item.text}</p><div class="g57Quiz">${['Hecho','Suposición'].map(x=>`<button data-g57-answer="${x}" class="${a===x?(a===item.answer?'correct':'wrong'):''}">${x==='Hecho'?'👁️':'💭'} ${x}</button>`).join('')}</div>${a?`<div class="g57Feedback">${a===item.answer?'¡Correcto!':'Revisemos juntos.'} ${item.why}</div>`:''}</div><div class="g57Footer"><button class="g57Button" data-g57-quiz-prev ${q===0?'disabled':''}>← Anterior</button><button class="g57Button" data-g57-quiz-next ${q===5?'disabled':''}>Siguiente afirmación →</button></div><label>Mi idea clave para Pages <input class="g57Input" data-g57-field="takeaway" value="${g57Esc(p.takeaway)}" placeholder="Observar no es lo mismo que suponer…"></label>`
}
function g57Seventh(s){let d=g57Data[7],p=g57Storage();
 if(s===0)return `<span class="g57Badge">4 min · Detector de fricción</span><h2>¿Qué nos hace perder tiempo?</h2><p class="g57Intro">Mira el aula o el patio durante 30 segundos. Encuentra una demora, confusión o desperdicio. Toca un ejemplo y formula otra observación propia.</p><div class="g57Visual"><div class="g57Scene"><span>⏳</span><span>🏫</span><span>🔎</span><small>Observamos el entorno con ojos de emprendedor.</small></div><div class="g57Ideas">${['⏳ Una fila larga','❔ Instrucciones confusas','🗑️ Algo se desperdicia'].map((x,i)=>`<button data-g57-friction="${i}" class="${p.friction===i?'active':''}">${x}</button>`).join('')}</div></div>${p.friction!==undefined?'<div class="g57Feedback">Describe qué viste, dónde y a quién afectó. Todavía no propongas una solución.</div>':''}<label>Mi observación <input class="g57Input" data-g57-field="observation" value="${g57Esc(p.observation)}" placeholder="Vi que… en…"></label>`;
 if(s===1){let i=g57State.quiz,item=d.sort[i],a=g57State.answers[i];return `<span class="g57Badge">5 min · Clasificación rápida</span><h2>Problema, síntoma o queja</h2><p class="g57Intro">Leemos la tarjeta y votamos. Después justificamos cómo convertiríamos una queja en una observación investigable.</p><div class="g57Case"><div class="g57Counter">Tarjeta ${i+1} / 4</div><p class="g57Statement">${item.text}</p><div class="g57Ideas">${['Problema','Síntoma','Queja'].map(x=>`<button data-g57-answer="${x}" class="${a===x?'active':''}">${x}</button>`).join('')}</div>${a?`<div class="g57Feedback">${a===item.answer?'Bien identificado.':'Pista para revisar:'} ${item.why}</div>`:''}</div><div class="g57Footer"><button class="g57Button" data-g57-quiz-prev ${i===0?'disabled':''}>← Anterior</button><button class="g57Button" data-g57-quiz-next ${i===3?'disabled':''}>Siguiente tarjeta →</button></div>`}
 if(s===2){let c=d.cases[g57State.case],stage=Number(p.reveal||0);return `<span class="g57Badge">16 min · De observación a oportunidad</span><h2>Laboratorio de oportunidades</h2><p class="g57Intro">Analizamos tres situaciones escolares. Elige una y revela cada capa con el grupo: observación → usuario → fricción → evidencia → impacto.</p><div class="g57Ideas">${d.cases.map((x,i)=>`<button data-g57-case="${i}" class="${i===g57State.case?'active':''}" style="text-align:center;font-size:1.3rem">${x.icon}<br>${x.title}</button>`).join('')}</div><div class="g57Problem"><b>${c.icon} Situación observada:</b> ${c.obs}</div><div class="g57Map">${[['👁️','Observación',c.obs],['👤','Usuario',c.user],['⚠️','Fricción',c.friction],['📋','Evidencia',c.evidence],['📈','Impacto',c.impact]].map((x,i)=>`<div class="${stage>=i?'lit':''}"><strong>${x[0]}</strong>${x[1]}${stage>=i?`<p>${x[2]}</p>`:''}</div>`).join('')}</div><div class="g57Footer"><button class="g57Button" data-g57-reveal ${stage>=4?'disabled':''}>Revelar siguiente pista →</button><span class="g57Counter">${stage+1} de 5 pistas</span></div><p class="g57Small">Antes de buscar soluciones, pregunta: ¿a quién escucharíamos y qué evidencia nos falta? La puntuación final requiere comprobar la situación en la escuela.</p>`}
 let words=(p.problem||'').trim().split(/\s+/).filter(Boolean);return `<span class="g57Badge">5 min · Desafío 12 palabras</span><h2>Un problema claro en 12 palabras</h2><p class="g57Intro">Cada equipo elige una de las tres situaciones. Escribe un problema que incluya usuario y fricción, con máximo 12 palabras. Léelo al curso.</p><div class="g57Ideas">${d.cases.map((x,i)=>`<button data-g57-case="${i}" class="${i===g57State.case?'active':''}">${x.icon} ${x.title}</button>`).join('')}</div><div class="g57Step"><b>Modelo:</b> «Estudiantes esperan demasiado al devolver libros durante el recreo».<label><span class="sr-only">Problema en doce palabras</span><input class="g57Input" data-g57-field="problem" value="${g57Esc(p.problem)}" placeholder="Los… necesitan… porque…"></label><p class="g57Counter" id="g57WordCount">${words.length} / 12 palabras ${words.length>12?'· reduce la frase':words.length?'· listo para revisar':''}</p></div><div class="g57Feedback">Revisión en equipo: ¿a quién afecta?, ¿qué dificultad concreta hay?, ¿qué observación la respalda? Si falta evidencia, indiquen qué deberían investigar.</div><button class="g57Button" data-g57-download-summary>Guardar tarjeta como imagen</button>`
}
function g57CanvasInit(){const canvas=document.getElementById('g57Canvas');if(!canvas)return;const r=canvas.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*scale);canvas.height=Math.round(r.height*scale);const ctx=canvas.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,r.height);g57State.history=[];let saved=g57Storage().canvas;if(saved){let img=new Image;img.onload=()=>ctx.drawImage(img,0,0,r.width,r.height);img.src=saved}let drawing=false;const point=e=>({x:e.clientX-canvas.getBoundingClientRect().left,y:e.clientY-canvas.getBoundingClientRect().top});canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);g57State.history.push(canvas.toDataURL());drawing=true;const q=point(e);ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(q.x+.1,q.y+.1);ctx.lineWidth=g57State.erase?32:Math.max(3,(e.pressure||.5)*8);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=g57State.erase?'#fff':g57State.ink;ctx.stroke()};canvas.onpointermove=e=>{if(!drawing)return;e.preventDefault();let q=point(e);ctx.lineTo(q.x,q.y);ctx.stroke()};canvas.onpointerup=canvas.onpointercancel=()=>{if(drawing){drawing=false;g57Save({canvas:canvas.toDataURL()})}}}
function g57CanvasRestore(src){const c=document.getElementById('g57Canvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);if(src){let im=new Image;im.onload=()=>ctx.drawImage(im,0,0,c.width,c.height);im.src=src}g57Save({canvas:src||null})}
function g57Download(url,filename){const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove()}
function g57Summary(){let c=document.createElement('canvas');c.width=1400;c.height=850;let x=c.getContext('2d'),p=g57Storage();x.fillStyle='#f0fafc';x.fillRect(0,0,c.width,c.height);x.fillStyle='#16b9cb';x.fillRect(25,25,1350,800);x.fillStyle='#fff';x.fillRect(43,43,1314,764);x.fillStyle='#17304c';x.font='bold 55px system-ui';x.fillText('🔎 Oportunidad emprendedora',80,130);x.font='32px system-ui';x.fillText(`7.º ${g57State.course||'A'} · Semana 4 · ${g57Date(p.date)}`,80,200);x.font='bold 38px system-ui';x.fillText('Nuestro problema en 12 palabras',80,295);x.font='36px system-ui';let words=(p.problem||'Escribe primero el problema de tu equipo.').split(' '),line='',y=370;for(let word of words){if(x.measureText(line+' '+word).width>1200){x.fillText(line,80,y);line=word;y+=55}else line+=(line?' ':'')+word}x.fillText(line,80,y);x.font='30px system-ui';x.fillText('Usuario · fricción · evidencia por investigar',80,710);g57Download(c.toDataURL('image/png'),'oportunidad-7-semana-4.png')}
function g57Action(e){if(![5,7].includes(activeGrade)||otherSession!==1)return;let t=e.target.closest('button');if(!t)return;let d=t.dataset;if(d.g57Step!==undefined){g57State.step=Number(d.g57Step);g57State.quiz=0;g57State.answers={};renderG57()}else if(d.g57Next!==undefined||d.g57Prev!==undefined){g57State.step=Math.max(0,Math.min(3,g57State.step+(d.g57Next!==undefined?1:-1)));g57State.quiz=0;g57State.answers={};renderG57()}else if(d.g57Course){g57State.course=d.g57Course;g57State.step=0;g57State.quiz=0;g57State.answers={};renderG57()}else if(d.g57Complete!==undefined){g57Save({complete:!g57Storage().complete});renderG57()}else if(d.g57Emotion!==undefined||d.g57Friction!==undefined){g57Save({[d.g57Emotion!==undefined?'emotion':'friction']:Number(d.g57Emotion??d.g57Friction)});renderG57()}else if(d.g57Case!==undefined){g57State.case=Number(d.g57Case);g57Save({reveal:0});renderG57()}else if(d.g57CaseNext!==undefined||d.g57CasePrev!==undefined){g57State.case=Math.max(0,Math.min(5,g57State.case+(d.g57CaseNext!==undefined?1:-1)));renderG57()}else if(d.g57Reveal!==undefined){g57Save({reveal:Math.min(4,Number(g57Storage().reveal||0)+1)});renderG57()}else if(d.g57Answer){g57State.answers[g57State.quiz]=d.g57Answer;renderG57()}else if(d.g57QuizNext!==undefined||d.g57QuizPrev!==undefined){g57State.quiz=Math.max(0,Math.min(activeGrade===5?5:3,g57State.quiz+(d.g57QuizNext!==undefined?1:-1)));renderG57()}else if(d.g57Ink){g57State.ink=d.g57Ink;g57State.erase=false;g57Root().querySelectorAll('.g57Tools button').forEach(x=>x.classList.remove('active'));t.classList.add('active')}else if(d.g57Erase!==undefined){g57State.erase=true;g57Root().querySelectorAll('.g57Tools button').forEach(x=>x.classList.remove('active'));t.classList.add('active')}else if(d.g57Undo!==undefined){let h=g57State.history?.pop();if(h)g57CanvasRestore(h)}else if(d.g57Clear!==undefined){let c=document.getElementById('g57Canvas');g57State.history.push(c.toDataURL());g57CanvasRestore(null)}else if(d.g57Download!==undefined){g57Download(document.getElementById('g57Canvas').toDataURL('image/png'),'veo-pienso-me-pregunto-5.png')}else if(d.g57DownloadSummary!==undefined)g57Summary()}
g57Root().addEventListener('click',g57Action);
g57Root().addEventListener('change',e=>{if(e.target.id==='g57Date'){g57Save({date:e.target.value});renderG57()}});
g57Root().addEventListener('input',e=>{let f=e.target.dataset.g57Field;if(!f)return;g57Save({[f]:e.target.value});if(f==='problem'){let n=e.target.value.trim().split(/\s+/).filter(Boolean).length;document.getElementById('g57WordCount').textContent=`${n} / 12 palabras ${n>12?'· reduce la frase':n?'· listo para revisar':''}`}});
