/* Marco de presentación 16:9; los módulos y datos de las clases se conservan. */
const deckState={page:0,key:'',pages:[]};
const deckHome=document.createElement('section');deckHome.id='deckHome';document.querySelector('.shell').append(deckHome);
const deckTools=document.createElement('div');deckTools.id='deckTools';deckTools.innerHTML='<button data-deckhome>⌂ Inicio</button><button data-deckfull>⛶ Pantalla completa</button><span id="deckPage"></span><button data-deckprev>← Pantalla anterior</button><button data-decknext>Pantalla siguiente →</button>';document.querySelector('.shell').append(deckTools);
function deckResize(){const scale=Math.min(innerWidth/1600,innerHeight/900);const shell=document.querySelector('.shell');shell.style.setProperty('--deck-scale',scale);shell.style.left=((innerWidth-1600*scale)/2)+'px';shell.style.top=((innerHeight-900*scale)/2)+'px'}
window.addEventListener('resize',deckResize);
function deckStart(g){deckHome.innerHTML=`<div class="deckWelcome"><button class="action" data-deckback>← Todos los cursos</button><div class="eyebrow">Elige tu clase</div><h1>${g==='dt'?'Design Thinking':g+'.º de básica'}</h1><p>Selecciona una planificación para comenzar.</p></div><div class="deckWeeks">${g==='dt'?dtPhases.map((p,i)=>`<button data-deckdt="${i+1}" style="--accent:${w5Colors[i]}"><span>${dtIcons[i]}</span><b>Sesión ${i+1}</b>${p}</button>`).join(''):[4,5].map(w=>`<article><h2>Semana ${w}</h2><p>${w===4?'28 sept.–2 oct.':'5–8 oct.'} · 2026</p><button data-deckgrade="${g}" data-deckweek="${w}" data-decks="1">Sesión 1 →</button><button data-deckgrade="${g}" data-deckweek="${w}" data-decks="2">Sesión 2 →</button></article>`).join('')}</div>`}
function deckShowHome(){clearInterval(w5.timer);if(typeof stopTimer==='function')stopTimer();document.body.classList.add('deck-home');document.body.classList.remove('deck-lesson','deck-weekfive','deck-design');deckHome.hidden=false;deckTools.hidden=true;document.getElementById('gradeFour').hidden=true;document.getElementById('otherGradeContent').hidden=true;w5Root.hidden=true;dtRoot.hidden=true;deckHome.innerHTML=`<div class="deckWelcome"><div class="eyebrow">Eight Academy · Aprendemos creando</div><h1>Planificación<br><em>Emprendimiento</em></h1><p>Explora, crea y transforma tus ideas.</p></div><div class="deckCourseGrid">${[[4,'Cuarto','🔎'],[5,'Quinto','💡'],[6,'Sexto','🛠️'],[7,'Séptimo','🚀'],['dt','Design Thinking','💛']].map(([g,t,icon],i)=>`<button data-deckcourse="${g}" style="--accent:${w5Colors[i]}"><span>${icon}</span><b>${t}</b><small>${g==='dt'?'Cinco fases · Un proyecto':'Planificaciones por semana'}</small><strong>Entrar →</strong></button>`).join('')}</div><div class="deckHomeFooter">Una idea pequeña puede convertirse en una gran solución.<button data-deckfull>⛶ Pantalla completa</button></div>`;deckResize()}
function deckEnter(){deckHome.hidden=true;deckTools.hidden=false;document.body.classList.remove('deck-home');document.body.classList.add('deck-lesson');document.body.classList.toggle('deck-weekfive',!w5Root.hidden);document.body.classList.toggle('deck-design',!dtRoot.hidden);deckPaginate()}
function deckLeaves(el){let out=[];for(const n of [...el.children]){if(n.classList.contains('timer'))continue;if((n.classList.contains('stage')||n.classList.contains('teamsGrid')||n.classList.contains('choices')||n.classList.contains('dtMap'))&&n.scrollHeight>420){out.push(...deckLeaves(n))}else out.push(n)}return out}
function deckPaginate(){const root=!w5Root.hidden?w5Root:!dtRoot.hidden?dtRoot:null;if(!root){document.getElementById('deckPage').textContent='Semana 4 · Vista original';deckState.pages=[];return}const card=root.querySelector(':scope > .card');if(!card){deckState.pages=[];document.getElementById('deckPage').textContent='Portada de la clase';return}const key=root.id==='weekFive'?`${w5.grade}${w5.course}-${w5.session}-${w5.step}-${w5.item}`:`dt-${dt.grade}${dt.course}-${dt.session}-${dt.step}`;if(deckState.key!==key){deckState.key=key;deckState.page=0}let wrap=card.querySelector(':scope > .deckContent');if(!wrap){wrap=document.createElement('div');wrap.className='deckContent';const nodes=deckLeaves(card);for(const n of nodes)wrap.append(n);for(const n of [...card.children])if(n.classList.contains('stage')||n.classList.contains('teamsGrid'))n.remove();card.prepend(wrap)}const nodes=[...wrap.children];nodes.forEach(n=>n.classList.remove('deck-hidden'));let pages=[[]],height=0;for(const n of nodes){const raw=n.getBoundingClientRect().height;const h=(raw?raw/(parseFloat(document.querySelector('.shell').style.getPropertyValue('--deck-scale'))||1)+12:0);if(height+h>410&&pages.at(-1).length){pages.push([]);height=0}pages.at(-1).push(n);height+=h}if(wrap.querySelector('.ndGrid'))pages=[nodes.filter(n=>!n.classList.contains('answer')),nodes.filter(n=>n.classList.contains('answer'))].filter(p=>p.length);deckState.pages=pages;deckState.page=Math.min(deckState.page,pages.length-1);deckPageRender()}
function deckPageRender(){deckState.pages.forEach((page,i)=>page.forEach(n=>n.classList.toggle('deck-hidden',i!==deckState.page)));document.getElementById('deckPage').textContent=deckState.pages.length?`Pantalla ${deckState.page+1} de ${deckState.pages.length}`:'Portada';deckTools.querySelector('[data-deckprev]').disabled=deckState.page<=0;deckTools.querySelector('[data-decknext]').disabled=deckState.page>=deckState.pages.length-1}
const deckW5Render=w5Render;w5Render=function(){deckW5Render();if(!deckHome.hidden) return;deckEnter()};
const deckW5Open=w5Open;w5Open=function(g,s){deckHome.hidden=true;deckW5Open(g,s);deckEnter()};
const deckSelect=selectGrade;selectGrade=function(g,s){deckHome.hidden=true;deckSelect(g,s);deckEnter()};
const deckDtRender=dtRender;dtRender=function(){deckDtRender();if(deckHome.hidden)deckEnter()};
const deckDtOpen=dtOpen;dtOpen=function(s){deckHome.hidden=true;deckDtOpen(s);deckEnter()};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.deckhome!==undefined||d.deckback!==undefined)deckShowHome();if(d.deckcourse!==undefined)deckStart(d.deckcourse==='dt'?'dt':+d.deckcourse);if(d.deckweek!==undefined){if(d.deckweek==='5')w5Open(+d.deckgrade,+d.decks);else selectGrade(+d.deckgrade,+d.decks)}if(d.deckdt!==undefined)dtOpen(+d.deckdt);if(d.deckprev!==undefined){deckState.page=Math.max(0,deckState.page-1);deckPageRender()}if(d.decknext!==undefined){deckState.page=Math.min(deckState.pages.length-1,deckState.page+1);deckPageRender()}if(d.deckfull!==undefined){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{b.textContent='Usa pantalla completa del navegador'}}});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&deckState.page<deckState.pages.length-1){deckState.page++;deckPageRender()}if(e.key==='ArrowLeft'&&deckState.page>0){deckState.page--;deckPageRender()}});
document.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'&&e.target.closest('.deckContent'))requestAnimationFrame(deckPaginate)},true);
document.body.classList.add('deck-enabled');deckShowHome();
