/* Cuarto · Semana 6: idear, construir, probar y mejorar. Datos separados por sesión y paralelo. */
const w6Root=document.createElement('section');w6Root.id='weekSix';w6Root.hidden=true;document.querySelector('.shell').append(w6Root);
const w6={session:1,course:'A',step:-1,screen:0,team:0,case:0,timer:null,remaining:0,rubric:false};
const w6Phases=['Activación','Anticipación','Construcción','Consolidación'];
const w6Lessons=[
 {title:'Ideas que ayudan',objective:'Proponer varias ideas para un problema del aula, elegir una que ayude y explicar por qué.',minutes:[4,5,16,5],guide:['Señalen el problema y elijan una respuesta. Tres casos, 1 minuto cada uno; cierre de 1 minuto.','Deslicen la comparación. Digan qué cambió y a quién ayuda. Tres casos y cierre en 5 minutos.','Grupos 1–5: observar 2 min, proponer 3 ideas 5 min, comparar y elegir 4 min, dibujar y preparar la explicación 5 min.','Cada grupo dispone de 40 segundos para mostrar su dibujo y explicar el porqué. Cierre y evaluación: 1 minuto.']},
 {title:'Construimos y probamos',objective:'Crear un modelo sencillo de la idea elegida, probarlo con otro grupo y realizar una mejora.',minutes:[3,4,18,5],guide:['Reconozcan la mejora en tres imágenes. Un minuto por caso.','Observen el modelo y respondan. Toquen las tres pistas: materiales, tamaño y uso.','Construir 8 min, probar con otro grupo 5 min, mejorar 3 min, preparar la presentación 2 min. Un modelo sirve para aprender; no tiene que ser perfecto.','Cada grupo muestra el modelo y cuenta qué cambió después de la prueba. Presentaciones de 40 segundos y cierre de 1 minuto.']}
];
const w6Cases=[
 {title:'El paso del aula',before:'mochilas',after:'ganchos',problem:'Las mochilas bloquean el paso.',need:'Caminar con seguridad.',ideas:['Ganchos a baja altura','Un estante para mochilas','Una zona para guardarlas'],quiz:['Las mochilas bloquean el paso','Faltan videojuegos','La pared necesita dibujos'],correct:0,solutions:['Comprar mochilas con luces','Guardar mochilas fuera del paso','Quitar los pupitres'],solution:1},
 {title:'El rincón de lectura',before:'libros',after:'biblioteca',problem:'Cuesta encontrar los libros.',need:'Encontrar un libro para leer.',ideas:['Separar por colores','Cajas por temas','Señales en el estante'],quiz:['Falta una consola','Cuesta encontrar los libros','Faltan dulces'],correct:1,solutions:['Amontonar más libros','Cerrar la biblioteca','Ordenar los libros por temas'],solution:2},
 {title:'Nuestro patio',before:'patio',after:'limpieza',problem:'Hay papeles en el suelo.',need:'Un patio limpio.',ideas:['Acercar el basurero','Puntos para separar residuos','Turnos para cuidar el patio'],quiz:['Faltan patines','Falta un pastel','Hay papeles en el suelo'],correct:2,solutions:['Poner puntos para separar residuos','Pintar los papeles','Esconder la basura'],solution:0}
];
const w6Esc=w5Esc;
function w6Key(session=w6.session){return `emprendimiento-semana6-4${w6.course}-s${session}`;}
function w6Read(session=w6.session){try{return JSON.parse(localStorage.getItem(w6Key(session))||'{}')}catch{return {}}}
function w6Save(patch){try{localStorage.setItem(w6Key(),JSON.stringify({...w6Read(),...patch}));return true}catch{w6Root.querySelector('[data-w6status]')?.replaceChildren('No se pudo guardar en este navegador.');return false}}
function w6Work(){const previous=w6.session===2?w6Read(1).teams?.[w6.team]:null;return {case:previous?.case??0,ideas:[],winner:previous?.winner||'',criteria:[],tests:{},change:'',improved:false,...w6Read().teams?.[w6.team]};}
function w6WriteWork(patch){const p=w6Read();return w6Save({teams:{...p.teams,[w6.team]:{...w6Work(),...patch}}});}
function w6Groups(){try{const p=JSON.parse(localStorage.getItem(`ea-cuarto-${w6.course}-equipos-semana4`)||'{}');return Array.from({length:5},(_,i)=>({id:i,name:p.names?.[i]||`Grupo ${i+1}`}))}catch{return Array.from({length:5},(_,i)=>({id:i,name:`Grupo ${i+1}`}))}}
function w6Image(name,alt){return `<button class="w6Photo" data-w6photo="${name}" aria-label="Ampliar imagen: ${w6Esc(alt)}"><img src="semana6/${name}.jpeg" alt="${w6Esc(alt)}"><span>⤢ Toca para ampliar</span></button>`;}
function w6Button(label,attrs='',primary=false,disabled=false){return `<button class="action ${primary?'primary':''}" ${attrs} ${disabled?'disabled':''}>${label}</button>`;}
function w6Head(title,prompt,tag=''){return `<header class="w6Head"><span>${tag||`${w6Lessons[w6.session-1].minutes[w6.step]} min · ${w6Phases[w6.step]}`}</span><h2>${title}</h2>${prompt?`<p>${prompt}</p>`:''}</header>`;}
function w6TeamSelect(){return `<label class="w6TeamLabel">Equipo <select data-w6team aria-label="Grupo de trabajo">${w6Groups().map(g=>`<option value="${g.id}" ${g.id===w6.team?'selected':''}>Grupo ${g.id+1}${g.name!==`Grupo ${g.id+1}`?' · '+w6Esc(g.name):''}</option>`).join('')}</select></label>`;}
function w6Nav(back,next){return `<nav class="w6Nav">${back||'<span></span>'}${next||'<span></span>'}</nav>`;}
function w6Screen(title,caption,photo,right,nav,extra=''){return `${w6Head(title,caption)}${extra}<div class="w6Columns">${photo}<section class="w6Task">${right}</section></div>${nav}`;}
function w6Options(options,key,correct){const a=w6Read().answers?.[key];return `<div class="w6Options">${options.map((x,i)=>w6Button(`${a===i?(i===correct?'✓ ':'● '):''}${w6Esc(x)}`,`data-w6answer="${key}" data-w6choice="${i}" data-w6correct="${correct}" aria-pressed="${a===i}"`,a===i)).join('')}</div>${a!==undefined?`<p class="w6Feedback ${a===correct?'good':'retry'}" role="status">${a===correct?'✓ ¡Buena elección! Expliquen por qué.':'💡 Miren la imagen y prueben otra vez.'}</p>`:''}`;}
function w6Quiz(){const i=w6.screen,c=w6Cases[i],isFirst=w6.session===1,anticipation=w6.step===1,key=`${w6.step}-${i}`,options=anticipation?c.solutions:(isFirst?c.quiz:c.solutions),correct=anticipation||!isFirst?c.solution:c.correct,ready=w6Read().answers?.[key]===correct;
 const title=anticipation?'Desliza y descubre':(isFirst?'Detectives: encuentren el problema':'¿Qué idea ayuda?');
 const photo=anticipation?w6Compare(c):w6Image(isFirst?c.before:c.after,anticipation?c.title:(isFirst?c.problem:c.solutions[c.solution]));
 return w6Screen(title,anticipation?'Compara el problema con una posible solución.':(isFirst?'Observen. Elijan. Expliquen.':'Elijan la idea que mejora la situación.'),photo,`<span class="w6CaseLabel">Caso ${i+1} de 3 · ${c.title}</span><h3>${anticipation||!isFirst?'¿Qué mejora la situación?':'¿Qué hay que mejorar?'}</h3>${w6Options(options,key,correct)}${anticipation?`<p class="w6Hint">Ayuda a: ${c.need.toLowerCase()}</p>`:''}`,w6Nav(w6Button(i?'← Caso anterior':'← Portada',i?`data-w6screen="${i-1}"`:'data-w6step="-1"'),w6Button(i<2?'Siguiente caso →':(w6.step===0?'Mirar las ideas →':'Crear nuestras ideas →'),i<2?`data-w6screen="${i+1}"`:`data-w6step="${w6.step+1}"`,true,!ready)));
}
function w6Compare(c){return `<div class="w6Compare"><div class="w6Comparison"><img src="semana6/${c.before}.jpeg" alt="Problema: ${c.problem}"><img class="w6After" src="semana6/${c.after}.jpeg" alt="Posible solución para ${c.need}" style="clip-path:inset(0 50% 0 0)"><span class="w6CompareTag left">Posible solución</span><span class="w6CompareTag right">Problema</span><div class="w6CompareLine" style="left:50%"></div></div><label>Desliza para comparar<input type="range" min="0" max="100" value="50" data-w6compare aria-label="Comparar problema y posible solución"></label></div>`;}
function w6BuildNav(max,ready=true){return w6Nav(w6Button(w6.screen?'← Paso anterior':'← Anticipación',w6.screen?`data-w6screen="${w6.screen-1}"`:'data-w6step="1"'),w6Button(w6.screen<max?'Siguiente misión →':'Presentar al curso →',w6.screen<max?`data-w6screen="${w6.screen+1}"`:'data-w6step="3"',true,!ready));}
function w6CaseChoices(work){return `<div class="w6CaseChoices">${w6Cases.map((c,i)=>w6Button(c.title,`data-w6case="${i}" aria-pressed="${work.case===i}"`,work.case===i)).join('')}</div>`;}
function w6S1Build(){const work=w6Work(),c=w6Cases[work.case],top=`<div class="w6MissionBar">${w6TeamSelect()}<div class="w6MiniSteps">${['Observar','Proponer','Elegir','Dibujar'].map((x,i)=>`<span class="${i===w6.screen?'active':''}">${i+1} · ${x}</span>`).join('')}</div></div>`;
 if(w6.screen===0)return w6Screen('Nuestro reto','Elijan una situación para ayudar.',w6Image(c.before,c.problem),`<h3>${c.problem}</h3>${w6CaseChoices(work)}<p class="w6Feedback">Necesitamos: ${c.need}</p><p class="w6Hint">Digan: «Queremos ayudar a…».</p>`,w6BuildNav(3),top);
 if(w6.screen===1)return w6Screen('Tres ideas, muchas posibilidades','Propongan primero. Elijan después.',w6Image(c.before,c.problem),`<h3>Banco de ideas · ${work.ideas.length} / 3</h3><div class="w6IdeaOptions">${c.ideas.map(x=>w6Button(`${work.ideas.includes(x)?'✓ ': '+ '}${x}`,`data-w6idea="${w6Esc(x)}" aria-pressed="${work.ideas.includes(x)}"`,work.ideas.includes(x))).join('')}</div><label class="w6Field">¿Otra idea?<div class="w6CustomIdea"><input maxlength="60" data-w6custom placeholder="Una idea del grupo…" aria-label="Idea propia del grupo">${w6Button('Añadir','data-w6add')}</div></label><div class="w6IdeaBank">${work.ideas.map(x=>`<span>${w6Esc(x)}</span>`).join('')}</div><p class="w6Hint">Toquen las ideas que quieren comparar.</p>`,w6BuildNav(3,work.ideas.length===3),top);
 if(w6.screen===2)return w6Screen('Voten por una idea','¿Cuál ayuda y podemos hacer?',w6Image(c.after,'Ejemplo de una posible mejora'),`<h3>La idea del grupo</h3><div class="w6IdeaOptions">${work.ideas.length?work.ideas.map(x=>w6Button(`${work.winner===x?'✓ ':''}${w6Esc(x)}`,`data-w6vote="${w6Esc(x)}" aria-pressed="${work.winner===x}"`,work.winner===x)).join(''):'<p>Vuelvan y propongan tres ideas.</p>'}</div><div class="w6Criteria">${['Ayuda','Es segura','Podemos hacerla'].map((x,i)=>w6Button(`${work.criteria.includes(i)?'✓ ':''}${x}`,`data-w6criterion="${i}" aria-pressed="${work.criteria.includes(i)}"`,work.criteria.includes(i))).join('')}</div><p class="w6Hint">Expliquen: «La elegimos porque…».</p>`,w6BuildNav(3,!!work.winner&&work.criteria.length===3),top);
 return w6Screen('Dibujen su solución','En una hoja: un dibujo grande y una frase.',w6Image(c.before,c.problem),`<div class="w6Chosen"><span>Idea elegida</span><h3>${w6Esc(work.winner)||'Elijan una idea en el paso anterior.'}</h3></div><div class="w6VisualInstructions"><p><b>1</b> Dibujen la idea.</p><p><b>2</b> Señalen cómo ayuda.</p><p><b>3</b> Expliquen el porqué.</p></div>${w6Button(`${work.drawn?'✓ ':''}Dibujo listo`,`data-w6drawn aria-pressed="${!!work.drawn}"`,work.drawn)}`,w6BuildNav(3,!!work.winner&&!!work.drawn),top);
}
function w6S2Anticipation(){const a=w6Read().answers?.model,clues=w6Read().modelClues||[];return w6Screen('Un modelo nos ayuda a aprender','Miren el ejemplo. ¿Para qué sirve?',w6Image('modelo','Ejemplo de un modelo de cartón para guardar mochilas'),`<h3>¿Para qué hacemos un modelo?</h3>${w6Options(['Para que brille','Para probar si ayuda','Para que cueste más'],'model',1)}<div class="w6Criteria">${['Materiales','Tamaño','Uso'].map((x,i)=>w6Button(`${clues.includes(i)?'✓ ':''}${x}`,`data-w6modelclue="${i}"`,clues.includes(i))).join('')}</div>${clues.length?`<p class="w6Hint" role="status">${['Papel y cartón: representar una idea.','Pequeño y claro: comprobar cómo funcionaría.','Otro grupo prueba: escuchamos qué mejorar.'][clues.at(-1)]}</p>`:''}`,w6Nav(w6Button('← Observar mejoras','data-w6step="0"'),w6Button('Construir nuestro modelo →','data-w6step="2"',true,a!==1||clues.length<3)));}
function w6S2Build(){const work=w6Work(),c=w6Cases[work.case],top=`<div class="w6MissionBar">${w6TeamSelect()}<div class="w6MiniSteps">${['Construir','Probar','Mejorar'].map((x,i)=>`<span class="${i===w6.screen?'active':''}">${i+1} · ${x}</span>`).join('')}</div></div>`;
 if(w6.screen===0)return w6Screen('De la idea al modelo','Usen papel, cartón y colores.',w6Image('modelo','Ejemplo: un modelo de cartón para guardar mochilas'),`<span class="w6CaseLabel">Idea de la sesión 1</span><h3>${w6Esc(work.winner)||'Elijan una idea para construir.'}</h3><details class="w6Compact"><summary>Elegir o cambiar la idea</summary>${w6CaseChoices(work)}${c.ideas.map(x=>w6Button(w6Esc(x),`data-w6setidea="${w6Esc(x)}"`,work.winner===x)).join('')}</details><div class="w6VisualInstructions"><p><b>1</b> Den forma a su idea.</p><p><b>2</b> Muestren cómo se usa.</p></div>${w6Button(`${work.built?'✓ ':''}Modelo listo`,`data-w6built aria-pressed="${!!work.built}"`,work.built)}<p class="w6Hint">La foto es un ejemplo. Construyan su propia solución.</p>`,w6BuildNav(2,!!work.winner&&!!work.built),top);
 if(w6.screen===1)return w6Screen('Otro grupo lo prueba','Muestren el modelo. Escuchen al equipo visitante.',w6Image('prueba','Un grupo de estudiantes prueba un modelo de cartón'),`<h3>¿Qué observaron?</h3><div class="w6TestRows">${['¿Se entiende?','¿Ayuda?','¿Es seguro?'].map((q,i)=>`<div><b>${q}</b>${['Sí','Aún no'].map((x,n)=>w6Button(x,`data-w6test="${i}" data-w6testvalue="${n===0}" aria-pressed="${work.tests[i]===String(n===0)}"`,work.tests[i]===String(n===0))).join('')}</div>`).join('')}</div><h4>¿Qué pueden mejorar?</h4><div class="w6Criteria">${['Tamaño','Lugar','Material','Más claridad'].map(x=>w6Button(x,`data-w6change="${x}" aria-pressed="${work.change===x}"`,work.change===x)).join('')}</div>`,w6BuildNav(2,Object.keys(work.tests).length===3&&!!work.change),top);
 return w6Screen('Una mejora que se nota','Cambien algo y vuelvan a probar.',w6Image('prueba','Volvemos a probar el modelo con el grupo'),`<div class="w6Chosen"><span>Nuestra mejora</span><h3>${w6Esc(work.change)||'Elijan una mejora en el paso anterior.'}</h3></div><div class="w6VisualInstructions"><p><b>1</b> Apliquen el cambio.</p><p><b>2</b> Prueben otra vez.</p><p><b>3</b> Cuenten qué mejoró.</p></div>${w6Button(`${work.improved?'✓ ':''}Mejora aplicada y probada`,`data-w6improved aria-pressed="${!!work.improved}"`,work.improved)}`,w6BuildNav(2,!!work.change&&!!work.improved),top);
}
function w6Presentation(){if(w6.rubric)return w6Rubric();const id=w6.screen,p=w6Read(),work=p.teams?.[id]||{},prev=w6Read(1).teams?.[id]||{},c=w6Cases[work.case??prev.case??0],presented=p.presented||[],done=presented.includes(id);return w6Screen(`Grupo ${id+1} · Muestren su idea`,w6.session===1?'Muestren el dibujo y expliquen en 40 segundos.':'Muestren el modelo y expliquen qué mejoró.',w6Image(w6.session===1?c.before:'prueba',w6.session===1?c.problem:'Un modelo se prueba en equipo'),`<div class="w6Chosen"><span>${w6.session===1?'Nuestra idea':'Nuestro modelo'}</span><h3>${w6Esc(work.winner||prev.winner)||'Muestren su trabajo al curso.'}</h3></div><div class="w6Pitch">${(w6.session===1?['El problema es…','Nuestra idea es…','Ayuda porque…']:['Construimos…','Al probar vimos…','Mejoramos…']).map((x,i)=>`<p><b>${i+1}</b>${x}</p>`).join('')}</div>${w6Button(`${done?'✓ ':''}El grupo presentó`,`data-w6presented="${id}" aria-pressed="${done}"`,done)}<p class="w6Hint">${presented.length} / 5 grupos presentaron.</p>`,w6Nav(w6Button(id?'← Grupo anterior':'← Nuestra misión',id?`data-w6screen="${id-1}"`:'data-w6step="2"'),w6Button(id<4?'Siguiente grupo →':'Ver rúbrica de grupos →',id<4?`data-w6screen="${id+1}"`:'data-w6rubric',true,!done||(id===4&&presented.length!==5))));}
function w6Rubric(){const p=w6Read(),criteria=[['Disciplina y códigos',2,'Respeta turnos y acuerdos.'],['Trabajo en equipo',2,'Participa y cumple su rol.'],['Actividad',4,w6.session===1?'Tres ideas: 2. Elegir y justificar: 2.':'Modelo: 2. Probar y mejorar: 2.'],['Orden y organización',2,'Cuida materiales y presenta su trabajo.']];return `${w6Head('Evaluación final · Grupos 1 a 5','Escribe los puntos. Total sobre 10.')}<div class="w6TableWrap"><table class="w6ScoreTable"><thead><tr><th>Criterio</th>${w6Groups().map(g=>`<th style="background:${w5Colors[g.id]}">Grupo ${g.id+1}</th>`).join('')}</tr></thead><tbody>${criteria.map(([title,max,desc],r)=>`<tr><th scope="row">${title}<small>${desc} · Máximo ${max}</small></th>${w6Groups().map(g=>`<td><input type="number" min="0" max="${max}" step="0.5" data-w6score="${r}" data-w6scoregroup="${g.id}" data-w6max="${max}" value="${p.scores?.[g.id]?.[r]??0}" aria-label="Grupo ${g.id+1} · ${title}"></td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr><th>Total / 10</th>${w6Groups().map(g=>`<td><output data-w6total="${g.id}" aria-label="Total Grupo ${g.id+1}">${w6Total(g.id)}</output></td>`).join('')}</tr></tfoot></table></div><p class="w6Hint">Guardado automático · 4.º ${w6.course} · Sesión ${w6.session}</p>${w6Nav(w6Button('← Revisar presentaciones','data-w6review'),w6Button(w6.session===1?'Ir a sesión 2 →':'Volver a la portada',w6.session===1?'data-w6open="2"':'data-w6step="-1"',true))}`;}
function w6Total(team){return (w6Read().scores?.[team]||[]).reduce((n,x)=>n+Number(x||0),0).toLocaleString('es-EC',{maximumFractionDigits:2})+' / 10';}
function w6Activity(){if(w6.step===3)return w6Presentation();if(w6.step===0||w6.session===1&&w6.step===1)return w6Quiz();if(w6.step===1)return w6S2Anticipation();return w6.session===1?w6S1Build():w6S2Build();}
function w6Guide(){const l=w6Lessons[w6.session-1];return `<details class="w6Guide"><summary>Guía docente</summary><p>${l.guide[w6.step]}</p><p><b>Materiales:</b> ${w6.session===1?'hojas, lápices y colores.':'papel, cartón, colores y cinta. Tijeras y soportes con supervisión docente.'}</p><p><b>Roles:</b> coordinador, portavoz, materiales, dibujante y verificador. Repartan los roles según sus integrantes.</p></details>`;}
function w6Cover(){const p=w6Read(),l=w6Lessons[w6.session-1];return `<div class="w6CoverTools"><div>${['A','B','C'].map(c=>w6Button(`4.º ${c}`,`data-w6course="${c}" aria-pressed="${w6.course===c}"`,w6.course===c)).join('')}</div><div>${[1,2].map(s=>w6Button(`Sesión ${s}`,`data-w6open="${s}" aria-pressed="${w6.session===s}"`,w6.session===s)).join('')}</div><label>Fecha <input type="date" data-w6date aria-label="Fecha de clase" value="${w6Esc(p.date)}"></label>${w6Button(p.complete?'✓ Completada':'○ Pendiente','data-w6complete',!!p.complete)}</div><div class="w6Cover"><div><span class="eyebrow">Cuarto de básica · Semana 6 · 12–16 oct. 2026</span><h1>${l.title}</h1><p><b>Objetivo:</b> ${l.objective}</p><div class="w6CoverPath">${(w6.session===1?['Proponer','Elegir','Dibujar']:['Construir','Probar','Mejorar']).map((x,i)=>`<span><b>${i+1}</b>${x}</span>`).join('')}</div>${w6Button('Comenzar misión →','data-w6step="0"',true)}<p class="w6Hint">30 minutos · 5 grupos · Rúbrica sobre 10</p></div>${w6Image(w6.session===1?'mochilas':'modelo',l.title)}</div>`;}
function w6Render(){w6Root.innerHTML=w6.step<0?w6Cover():`<section class="card w6Card"><div class="w6Panel">${w6Activity()}<footer class="w6LessonFooter">${w6Guide()}<span data-w6status aria-live="polite"></span><div class="w6Timer"><output data-w6clock>${w6Clock()}</output>${w6Button(w6.timer?'Pausar':'Iniciar tiempo','data-w6timer')}${w6Button('Reiniciar','data-w6reset')}</div></footer></div></section>`;w6Enter();}
function w6Active(){return !w6Root.hidden;}
function w6Clock(){return Math.floor(w6.remaining/60)+':'+String(w6.remaining%60).padStart(2,'0');}
function w6Stop(){clearInterval(w6.timer);w6.timer=null;}
function w6Step(step){w6Stop();w6.step=Math.max(-1,Math.min(3,step));w6.screen=0;w6.rubric=false;w6.remaining=w6.step>=0?w6Lessons[w6.session-1].minutes[w6.step]*60:0;w6Render();}
function w6Open(session){w6Stop();clearInterval(w5.timer);if(typeof stopTimer==='function')stopTimer();activeWeek=6;w6.session=Math.max(1,Math.min(2,session));w6.step=-1;w6.screen=0;w6.rubric=false;w6Root.hidden=false;w5Root.hidden=true;dtRoot.hidden=true;document.getElementById('gradeFour').hidden=true;document.getElementById('otherGradeContent').hidden=true;deckHome.hidden=true;w6Render();}
function w6Enter(){deckHome.hidden=true;deckTools.hidden=false;document.body.classList.remove('deck-home','deck-design','deck-detectives','deck-aula','deck-aula-routine','deck-s1photos');document.body.classList.add('deck-lesson','deck-weekfive','deck-week6');document.body.classList.toggle('deck-activity',w6.step>=0);deckState.pages=[];const moment=document.getElementById('deckMoment');moment.hidden=w6.step<0;if(w6.step>=0)moment.value=String(w6.step);document.getElementById('deckPage').textContent=w6.step<0?'Semana 6 · Portada':w6Phases[w6.step];for(const d of ['deckprev','decknext'])deckTools.querySelector(`[data-${d}]`).hidden=true;const oldSound=deckTools.querySelector('[data-aulasound]');if(oldSound)oldSound.hidden=true;w6SoundButton.hidden=w6.step<0;w6SoundButton.textContent=aulaSoundEnabled?'🔊 Sonido':'🔇 Silenciado';w6SoundButton.setAttribute('aria-pressed',String(aulaSoundEnabled));deckResize();}
const w6SoundButton=document.createElement('button');w6SoundButton.dataset.w6sound='';w6SoundButton.hidden=true;w6SoundButton.setAttribute('aria-label','Sonidos de acierto');deckTools.insertBefore(w6SoundButton,document.getElementById('deckPage'));
function w6Hide(){w6Stop();w6Root.hidden=true;w6SoundButton.hidden=true;document.body.classList.remove('deck-week6');}
const w6OldHome=deckShowHome;deckShowHome=function(){w6Hide();w6OldHome();};
const w6OldW5Open=w5Open;w5Open=function(g,s){w6Hide();w6OldW5Open(g,s);};
const w6OldSelect=selectGrade;selectGrade=function(g,s){w6Hide();w6OldSelect(g,s);};
const w6OldDtOpen=dtOpen;dtOpen=function(s){w6Hide();w6OldDtOpen(s);};
const w6OldStart=deckStart;deckStart=function(g){w6OldStart(g);if(Number(g)===4){const weeks=deckHome.querySelector('.deckWeeks');weeks.classList.add('w6Weeks');weeks.insertAdjacentHTML('beforeend',`<article class="w6NewWeek"><span>Nueva planificación</span><h2>Semana 6</h2><p>12–16 oct. · 2026</p>${w6Button('Sesión 1 →','data-w6open="1"')}${w6Button('Sesión 2 →','data-w6open="2"')}</article>`);}};
const w6LegacyMenu=weekMenu.querySelector('.weekDropdown>details');w6LegacyMenu.insertAdjacentHTML('beforeend',`<div class="weekLinks"><b>Semana 6</b>${w6Button('Sesión 1','data-w6open="1"')}${w6Button('Sesión 2','data-w6open="2"')}</div>`);
document.getElementById('deckMoment').addEventListener('change',e=>{if(!w6Active())return;e.stopImmediatePropagation();w6Step(Number(e.target.value));},true);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.w6open!==undefined){e.stopImmediatePropagation();weekMenu.open=false;w6Open(+d.w6open);return;}if(d.w6sound!==undefined){e.stopImmediatePropagation();aulaSoundEnabled=!aulaSoundEnabled;try{localStorage.setItem('aula-success-sound',aulaSoundEnabled?'on':'off')}catch{}w6Enter();if(aulaSoundEnabled)aulaPlaySuccess();return;}if(w6Active()&&d.deckcover!==undefined){e.stopImmediatePropagation();w6Step(-1);}},true);
w6Root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset,p=w6Read(),work=w6Work();
 if(d.w6step!==undefined){w6Step(+d.w6step);return;}
 if(d.w6course){w6.course=d.w6course;w6.team=0;w6Step(-1);return;}
 if(d.w6complete!==undefined){w6Save({complete:!p.complete});w6Render();return;}
 if(d.w6photo){const dialog=document.createElement('dialog');dialog.className='w6ImageDialog';dialog.setAttribute('aria-label','Imagen ampliada');dialog.innerHTML=`<form method="dialog">${w6Button('Cerrar imagen ✕')}</form><img src="semana6/${d.w6photo}.jpeg" alt="Fotografía ampliada de la actividad">`;dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();return;}
 if(d.w6timer!==undefined){if(w6.timer)w6Stop();else{w6.timer=setInterval(()=>{w6.remaining=Math.max(0,w6.remaining-1);const clock=w6Root.querySelector('[data-w6clock]');if(clock)clock.textContent=w6.remaining?w6Clock():'¡A compartir!';if(!w6.remaining){w6Stop();const btn=w6Root.querySelector('[data-w6timer]');if(btn)btn.textContent='Iniciar tiempo';}},1000);}b.textContent=w6.timer?'Pausar':'Iniciar tiempo';return;}
 if(d.w6reset!==undefined){w6Stop();w6.remaining=w6Lessons[w6.session-1].minutes[w6.step]*60;w6Render();return;}
 if(d.w6screen!==undefined){w6.screen=+d.w6screen;w6Render();return;}
 if(d.w6answer!==undefined){const selected=+d.w6choice;w6Save({answers:{...p.answers,[d.w6answer]:selected}});if(selected===+d.w6correct)aulaPlaySuccess();}
 else if(d.w6case!==undefined){const n=+d.w6case;if(n!==work.case)w6WriteWork({case:n,ideas:[],winner:'',criteria:[],drawn:false,built:false,tests:{},change:'',improved:false});}
 else if(d.w6idea){const ideas=[...work.ideas],at=ideas.indexOf(d.w6idea);if(at>=0){ideas.splice(at,1);w6WriteWork({ideas,winner:work.winner===d.w6idea?'':work.winner,drawn:false});}else if(ideas.length<3)w6WriteWork({ideas:[...ideas,d.w6idea]});}
 else if(d.w6add!==undefined){const input=w6Root.querySelector('[data-w6custom]'),idea=input.value.trim();if(idea&&work.ideas.length<3&&!work.ideas.includes(idea))w6WriteWork({ideas:[...work.ideas,idea]});else{input.setAttribute('aria-invalid','true');input.placeholder=work.ideas.length>=3?'Ya tienen tres ideas.':'Escriban una idea diferente.';return;}}
 else if(d.w6vote)w6WriteWork({winner:d.w6vote,drawn:false});
 else if(d.w6criterion!==undefined){const n=+d.w6criterion;w6WriteWork({criteria:work.criteria.includes(n)?work.criteria.filter(x=>x!==n):[...work.criteria,n]});}
 else if(d.w6drawn!==undefined)w6WriteWork({drawn:!work.drawn});
 else if(d.w6modelclue!==undefined){const n=+d.w6modelclue;w6Save({modelClues:[...(p.modelClues||[]).filter(x=>x!==n),n]});}
 else if(d.w6setidea)w6WriteWork({winner:d.w6setidea,built:false});
 else if(d.w6built!==undefined)w6WriteWork({built:!work.built});
 else if(d.w6test!==undefined)w6WriteWork({tests:{...work.tests,[d.w6test]:d.w6testvalue},improved:false});
 else if(d.w6change)w6WriteWork({change:d.w6change,improved:false});
 else if(d.w6improved!==undefined)w6WriteWork({improved:!work.improved});
 else if(d.w6presented!==undefined){const n=+d.w6presented,ids=p.presented||[];w6Save({presented:ids.includes(n)?ids.filter(x=>x!==n):[...ids,n]});}
 else if(d.w6rubric!==undefined)w6.rubric=true;
 else if(d.w6review!==undefined){w6.rubric=false;w6.screen=4;}
 else return;w6Render();
});
w6Root.addEventListener('change',e=>{const d=e.target.dataset;if(d.w6team!==undefined){w6.team=+e.target.value;w6Render();}else if(d.w6date!==undefined)w6Save({date:e.target.value});else if(d.w6score!==undefined){e.target.value=Math.max(0,Math.min(+d.w6max,Number(e.target.value)||0));w6StoreScore(e.target);}});
function w6StoreScore(input){const d=input.dataset,p=w6Read(),r=+d.w6score,g=+d.w6scoregroup,row=[...(p.scores?.[g]||[0,0,0,0])];row[r]=Math.round(Math.max(0,Math.min(+d.w6max,Number(input.value)||0))*100)/100;w6Save({scores:{...p.scores,[g]:row}});w6Root.querySelector(`[data-w6total="${g}"]`).textContent=w6Total(g);}
w6Root.addEventListener('input',e=>{const d=e.target.dataset;if(d.w6compare!==undefined){const n=+e.target.value,box=e.target.closest('.w6Compare');box.querySelector('.w6After').style.clipPath=`inset(0 ${100-n}% 0 0)`;box.querySelector('.w6CompareLine').style.left=n+'%';}else if(d.w6score!==undefined)w6StoreScore(e.target);});
const w6Params=new URLSearchParams(location.search);if(w6Params.get('semana')==='6'){w6.course=['A','B','C'].includes(w6Params.get('curso'))?w6Params.get('curso'):'A';w6Open(Number(w6Params.get('sesion'))||1);}
